---
- name: Get Vcenter and  VM details
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Extract datacenter name
    ansible.builtin.set_fact:
      Vcenter_Name: "{{ hostvars[variables.server | upper]['tag_category']['vcenter'] | first }}"

  - name: display info
    ansible.builtin.debug: 
      msg: "{{ Vcenter_Name }}"

  - name: set vminfo variable
    block:
      - name: Gather all registered virtual machines with lowercase variables.server
        community.vmware.vmware_vm_info:
          hostname: '{{ Vcenter_Name }}'
          username: '{{ VMWARE_USERNAME }}'
          password: '{{ VMWARE_PASSWORD }}'
          vm_name: "{{ variables.server | lower }}"
          validate_certs: false
        register: vminfo
 
    rescue:
      - name: Gather all registered virtual machines with uppercase variables.server
        community.vmware.vmware_vm_info:
          hostname: '{{ Vcenter_Name }}'
          username: '{{ VMWARE_USERNAME }}'
          password: '{{ VMWARE_PASSWORD }}'
          vm_name: "{{ variables.server | upper }}"
          validate_certs: false
        register: vminfo
 
  - name: display info
    ansible.builtin.debug: var=vminfo
     
 
  # - ansible.builtin.set_stats:
  #       data:
  #         Vcenter_Name: "{{ Vcenter_Name }}"
  #         VM_servername: "{{ actual_guest_name }}"
