---
- name: Device Unreachable automation
  hosts: all
  gather_facts: no
  ignore_errors: yes
  collections:
    - ansible.windows
  tasks:
     - name: Perform Windows ping
       win_ping:
       register: ping_result

     - name: Display success or failure message
       debug:
         msg: "Ping was successful!"
       when: ping_result.ping is defined and ping_result.ping

     - debug:
         msg: "Ping failed!"
       when: ping_result.ping is not defined or not ping_result.ping
