---
- name: Calculate time difference
  hosts: localhost
  gather_facts: no

  vars:
    downtime_windows_end: "2024-08-03 14:00:07"
    Downtime_Windows_Start: "2024-08-02 14:00:00"

  tasks:
  - name: Calculate time difference
    set_fact:
      time_diff: "{{ '%Y-%m-%d %H:%M:%S' | strftime(downtime_windows_end) - '%Y-%m-%d %H:%M:%S' | strftime(Downtime_Windows_Start) }}"

  - name: Convert time difference to minutes
    set_fact:
      time_diff_minutes: "{{ (time_diff.seconds + time_diff.days * 24 * 60 * 60) / 60 }}"

  - name: Print time difference in minutes
    debug:
      msg: "Time difference: {{ time_diff_minutes }} minutes"
