---
- name: Server time Identification
  hosts: localhost
  gather_facts: no
  tasks:      
    - name: Get current time in UTC
      ansible.builtin.debug:
         msg: "Current time (UTC): {{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"
