---
- name: Calculate time difference
  hosts: localhost
  gather_facts: no

  vars:
    downtime_windows_start: "2024-09-04 17:14:59"
    downtime_windows_end: "2024-09-04 17:20:12"
  #  select_date_and_time: "Immediately"
  #  please_select_server_reboot_time: "Immediately"
    # please_select_server_reboot_time: "Future Date" 
    # Start_Date: "2024-09-06 07:28:00"
    # End_Date: "2024-09-07 07:25:46"
    please_select_server_shutdown_time: "Immediately"
    shutdown_period: "2024-09-07"

  tasks:
  - name: Calculate SL maintenance duration for CPU or MEM
    block:
      - name: Calculate the difference in seconds
        set_fact:
          seconds_diff: "{{ ((downtime_windows_end | to_datetime('%Y-%m-%d %H:%M:%S') - downtime_windows_start | to_datetime('%Y-%m-%d %H:%M:%S')).total_seconds()) | float }}"

      - name: Convert seconds difference to minutes
        set_fact:
          minutes_duration: "{{ (seconds_diff | float / 60) | int }}"
    when: select_date_and_time is defined and select_date_and_time == "Future Date"

  - name: Calculate SL maintenance duration for Reboot
    block:
      - name: Calculate the difference in seconds
        set_fact:
          seconds_diff: "{{ ((End_Date | to_datetime('%Y-%m-%d %H:%M:%S') - Start_Date | to_datetime('%Y-%m-%d %H:%M:%S')).total_seconds()) | float }}"

      - name: Convert seconds difference to minutes
        set_fact:
          minutes_duration: "{{ (seconds_diff | float / 60) | int }}"
    when: please_select_server_reboot_time is defined and please_select_server_reboot_time == "Future Date"  

  - name: Get current time in UTC
    ansible.builtin.set_fact:
      current_time_utc: "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"
    when: please_select_server_shutdown_time is defined 

  - name: Calculate SL maintenance duration for Shutdown
    block:
      - name: Ensure shutdown_period has a time component
        set_fact:
          shutdown_period_with_time: "{{ shutdown_period + ' 00:00:00' }}"

      - name: Calculate the difference in seconds
        set_fact:
          seconds_diff: "{{ ((shutdown_period_with_time | to_datetime('%Y-%m-%d %H:%M:%S') - current_time_utc | to_datetime('%Y-%m-%d %H:%M:%S')).total_seconds()) | float }}"
      
      - name: Convert seconds difference to minutes
        set_fact:
          minutes_duration: "{{ (seconds_diff | float / 60) | int }}"
    when: please_select_server_shutdown_time is defined 

  - name: Set SL minutes duration to 30 when reboot, CPU and MEM task performed immediately
    set_fact:
        minutes_duration: 30
    when: (please_select_server_reboot_time | default('') == "Immediately") or (select_date_and_time | default('') == "Immediately")
    
  - name: Show the minutes difference
    debug:
      msg: "The difference is {{  minutes_duration }} minutes"
