---
- name: Server time Identification
  hosts: localhost
  gather_facts: no
  tasks:      
    - name: Gather VM information
      community.vmware.vmware_vm_info:
         hostname: '{{ Vcenter_Name }}'
         username: '{{ VMWARE_USERNAME }}'
         password: '{{ VMWARE_PASSWORD }}'
         vm_name: "{{ VM_servername }}"
         validate_certs: false
      register: vm_info

    - ansible.builtin.debug: var=vm_info
        
    - name: Filter datacenter value
      ansible.builtin.set_fact:
        datacenter_value: "{{ vm_info.virtual_machines[0].datacenter }}"

    - name: Find folder path of a virtual machine
      community.vmware.vmware_guest_find:
        hostname: "{{ Vcenter_Name }}"
        username: "{{ VMWARE_USERNAME }}"
        password: "{{ VMWARE_PASSWORD }}"
        name: "{{ VM_servername }}"
        validate_certs: false
      register: vm_folder

    - name: Print the folder path
      debug:
        var: vm_folder.folders

    - name: Get VM folder details
      set_fact:
        VM_folder: "{{ vm_folder.folders | first }}"

    - name: Get VM info
      community.vmware.vmware_vm_info:
         hostname: "{{ Vcenter_Name }}"
         username: "{{ VMWARE_USERNAME }}"
         password: "{{ VMWARE_PASSWORD }}"
         datacenter: "{{ datacenter_value }}"
         folder: "/{{ datacenter_value }}/vm/{{ vm_folder }}"
         name: "{{ VM_servername }}"
      register: VM_info

    - name: Get VM ID
      set_fact:
        VM_id: "{{ VM_info.virtual_machines.vm_id }}"
