---
- name: Get Vcenter vm details
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Extract datacenter name
    set_fact:
      Vcenter_Name: "{{ hostvars[variables.server | upper]['tag_category']['vcenter'] | first }}"

  - name: display info
    debug: 
      msg: "{{ Vcenter_Name }}"

  - name: Gather all registered virtual machines
    community.vmware.vmware_vm_info:
      hostname: '{{ Vcenter_Name }}'
      username: '{{ VMWARE_USERNAME }}'
      password: '{{ VMWARE_PASSWORD }}'
      validate_certs: false
    register: all_servers

  # - name: Display all VM guest names
  #   debug:
  #       msg: "{{ all_servers.virtual_machines | map(attribute='guest_name') | list }}"

  # - name: Display all VM guest names in lowercase
  #   debug:
  #      msg: "{{ all_servers.virtual_machines | map(attribute='guest_name') | map('lower') | list }}"

  - name: Create a list with guest names and their lowercase versions
    set_fact:
      vm_guest_names: >
        {{
          all_servers.virtual_machines | 
          map(lambda item: {
            'guest_name': item.guest_name, 
            'guest_name_lower': item.guest_name | lower
          }) | 
          list
        }}
      
  - name: Find and set the actual guest name for a given host_name
    set_fact:
      actual_guest_name: >
        {{
          (vm_guest_names | 
          selectattr('guest_name_lower', 'equalto', variables.server) | 
          map(attribute='guest_name') | 
          first) | 
          default('Not Found')
        }}

  - name: Display the actual guest name
    debug:
      msg: "The actual guest name for '{{ variables.server }}' is '{{ actual_guest_name }}'"

  # - name: Manually filter servers case-insensitively
  #   set_fact:
  #       matched_servers: >-
  #         {{
  #           all_servers.virtual_machines |
  #           selectattr('guest_name', 'defined') |
  #           selectattr('guest_name', 'search', variables.server | lower) |
  #           map(attribute='guest_name') |
  #           list
  #         }}

  # - name: Display matched servers
  #   debug:
  #     msg: "{{ matched_servers }}"

  # - name: Reboot the virtual machine
  #   community.vmware.vmware_guest_powerstate:
  #      hostname: '{{ Vcenter_Name }}'
  #      username: '{{ VMWARE_USERNAME }}'
  #      password: '{{ VMWARE_PASSWORD }}'
  #      validate_certs: false
  #      name: "{{ server_name }}"
  #      state: reboot-guest
  
