---
- name: Get Vcenter vm details
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Extract datacenter name
    set_fact:
      Vcenter_Name: "{{ hostvars[server_name]['tag_category']['vcenter'] }}"

  - name: display info
    debug: 
      msg: "{{ Vcenter_Name }}"

  - name: Gather all registered virtual machines
    community.vmware.vmware_vm_info:
      hostname: '{{ Vcenter_Name }}'
      username: '{{ VMWARE_USERNAME }}'
      password: '{{ VMWARE_PASSWORD }}'
      vm_name: "{{ server_name }}"
      validate_certs: false
    register: vminfo

  - debug:
      var: vminfo


#  - name: Get the VM inventory
#    vmware.vmware_rest.vcenter_vm_info:
#      vcenter_hostname: "{{ datacenter_name }}"
#      vcenter_username: "{{ VMWARE_USERNAME }}"
#      vcenter_password: "{{ VMWARE_PASSWORD }}" 
#      vcenter_validate_certs: false
#      filter_names: 
#      - "{{ server_name }}"
#    register: vm_fact
      
