---
- name: Calculate time difference
  hosts: localhost
  gather_facts: no

  vars:
    downtime_windows_end: "2024-08-03 14:00:07"
    Downtime_Windows_Start: "2024-08-02 14:00:00"

  tasks:
  - name: Calculate time difference
    set_fact:
      time_diff: "{{ (downtime_windows_end | to_datetime) - (Downtime_Windows_Start | to_datetime) }}"
    register: time_diff_output

  - debug:
      var: time_diff_output

  - name: Convert time difference to minutes
    set_fact:
      time_diff_minutes: "{{ (time_diff_output.ansible_facts.time_diff.split(', ')[0] | regex_replace(' day', '') | int) * 1440 + (time_diff_output.ansible_facts.time_diff.split(', ')[1] | regex_replace(':', ' ') | split(' ')[0] | int) * 60 + (time_diff_output.ansible_facts.time_diff.split(', ')[1] | regex_replace(':', ' ') | split(' ')[1] | int) }}"

  - debug:
      msg: "Time difference: {{ time_diff_minutes }} minutes"
      
  # - name: Convert time difference to minutes
  #   set_fact:
  #     time_diff_minutes: "{{ time_diff.seconds / 60 + time_diff.days * 24 * 60 }}"

  # - name: Print time difference in minutes
  #   debug:
  #     msg: "Time difference: {{ time_diff_minutes }} minutes"
