---
- name: Calculate time difference
  hosts: localhost
  gather_facts: no

  vars:
    downtime_windows_end: "2024-08-03 14:00:07"
    Downtime_Windows_Start: "2024-08-02 14:00:00"

  tasks:
  - name: Calculate time difference
    set_fact:
      time_diff: "{{ (downtime_windows_end | to_datetime) - (Downtime_Windows_Start | to_datetime) }}"
    register: time_diff_output

  - debug:
      var: time_diff_output

  - name: Convert a duration into minutes
    ansible.builtin.debug:
      msg: "{{ '30h 20m 10s 123ms' | community.general.to_minutes }}"
 
  - name: Convert time difference to minutes
    set_fact:
       time_diff_minutes: "{{ time_diff_output.ansible_facts.time_diff | community.general.to_minutes }}"
    register: time_diff_minutes_output

  - debug:
      var: time_diff_minutes_output
