---
- name: Get Vcenter vm details
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Extract datacenter name
    set_fact:
      Vcenter_Name: "{{ hostvars[server_name]['tag_category']['vcenter'] | first }}"

  - name: display info
    debug: 
      msg: "{{ Vcenter_Name }}"

  - name: Gather all registered virtual machines
    community.vmware.vmware_vm_info:
      hostname: '{{ Vcenter_Name }}'
      username: '{{ VMWARE_USERNAME }}'
      password: '{{ VMWARE_PASSWORD }}'
      vm_name: "{{ server_name }}"
      validate_certs: false
    register: vminfo

  - name: Reboot the virtual machine
    community.vmware.vmware_guest_powerstate:
       name: "{{ server_name }}"
         state: reboot-guest
  
