---
- name: Calculate time difference
  hosts: localhost
  gather_facts: no

  vars:
    downtime_windows_start: "2024-08-02 14:00:00"
    downtime_windows_end: "2024-08-03 14:00:07"

  tasks:
  - name: Calculate the difference in seconds
    set_fact:
        seconds_diff: "{{ ((downtime_windows_end | to_datetime('%Y-%m-%d %H:%M:%S') - downtime_windows_start | to_datetime('%Y-%m-%d %H:%M:%S')).total_seconds()) | float }}"

  - name: Convert seconds difference to minutes
    set_fact:
      minutes_duration: "{{ (seconds_diff | float / 60) | int }}"

  # - name: Show the minutes difference
  #   debug:
  #     msg: "The difference is {{ minutes_diff }} minutes"
