---
- name: Server time Identification
  hosts: localhost
  gather_facts: no
  tasks:      
    - name: Get current time in UTC
      ansible.builtin.set_fact:
        current_time_utc: "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"

    - name: Show the current time variable
      ansible.builtin.debug:
        var: current_time_utc

    - name: Convert UTC time to Unix timestamp
      ansible.builtin.command:
        argv:
          - "date"
          - "-u"
          - "-d"
          - "{{ current_time_utc }}"
          - "+%s"
      register: timestamp_result

    - name: Show Unix timestamp
      ansible.builtin.debug:
        msg: "Unix timestamp: {{ timestamp_result.stdout }}"

