---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Grab token using OAuth
      ansible.builtin.uri:
        url: "{{ SN_HOST }}/oauth_token.do"
        method: POST
        body_format: form-urlencoded
        return_content: true
        body:
          grant_type : password
          client_id : "{{ SN_CLIENT_ID }}"
          client_secret : "{{ SN_CLIENT_SECERT }}"
          username : "{{ SN_USERNAME }}"
          password : "{{ SN_PASSWORD }}"
      register: oauth_return_token

    - name: Get the token
      debug: 
        var: "{{ oauth_return_token.json.access_token }}"
