---
- hosts: localhost
  connection: local
  collections:
    - community.general
  vars:
     nios_provider:
        host: "{{ INFOBLOX_HOST }}"
        username: "{{ INFOBLOX_USERNAME }}"
        password: "{{ INFOBLOX_PASSWORD }}"

  tasks:
  - name: Get next available IP
    set_fact:
      next_ip: "{{ lookup('infoblox.nios_modules.nios_next_ip', '10.17.113.0/24', provider=nios_provider) }}"

  - name: Print the next available IP
    debug:
      msg: "Next available IP: {{ next_ip }}"

  - set_stats:
      data:
        server_ip: "{{ next_ip }}"  

  - name: Read CSV file
    community.general.read_csv:
      path: DC1B-VMware-mapping.csv
      delimiter: ','
    register: csv_data

  - name: Install application based on condition
    debug:
       msg: "{{ item.Vm_name }}"
    when: item.Datacenter_location_input == 'DC1B' and item.Network_zone_Input == 'IDZ' and item.Environment_input == 'Stage' 
    loop: "{{ csv_data.list }}"
    loop_control:
      loop_var: item

 
