---
- hosts: localhost
  connection: local
  collections:
    - infoblox.nios_modules
  vars:
     nios_provider:
        host: "{{ INFOBLOX_HOST }}"
        username: "{{ INFOBLOX_USERNAME }}"
        password: "{{ INFOBLOX_PASSWORD }}"

  tasks:
  - name: Get next available IP
    set_fact:
      next_ip: "{{ lookup('infoblox.nios_modules.nios_next_ip', '10.17.113.0/24', provider=nios_provider") }}"

  - name: Print the next available IP
    debug:
      msg: "Next available IP: {{ next_ip }}"
