---
- hosts: localhost
  connection: local
  collections:
    - community.general

  vars:
    network_zone: "IDZ – Internal DMZ"

  tasks:
  - name: Split string
    set_fact:
      zone_network: "{{ variables.network_zone | split(' – ') }}"

  - name: Print network zone
    debug:
      var: zone_network
  
