---
- hosts: localhost
  connection: local
  collections:
    - community.general
  tasks:
    - name: Split string
      set_fact:
        zone_network: "{{ variables.network_zone.split(' – ') }}"

    - name: Print network zone 
      debug:
        var: zone_network

    - name: Set network zone 
      set_fact:
        zone_network: "{{ zone_network[0] }}"

    - name: Print network zone (filtered to first element)
      debug:
        var: zone_network

    - name: Extract Datacenter Code
      set_fact:
        location_datacenter: "{{ variables.Datacenter_Location | regex_replace('.* - ([^(]*) .*', '\\1') }}"

    - name: Print Datacenter Code
      debug:
        var: location_datacenter

    - name: Set zone_network to first element only
      set_fact:
        location_environment: "{{ variables.Environment }}"

    - name: Print Environment
      debug:
        var: location_environment

    - name: Extract Application Type Abbreviation
      set_fact:
        type_of_app: "{{ variables.application_type.split(' ')[0] }}"

    - name: Print Application Type Abbreviation
      debug:
        var: type_of_app
