---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Grab token using OAuth
      ansible.builtin.uri:
        url: "{{ SN_HOST }}/oauth_token.do"
        method: POST
        body_format: form-urlencoded
        return_content: true
        body:
          grant_type : password
          client_id : "{{ SN_CLIENT_ID }}"
          client_secret : "{{ SN_CLIENT_SECERT }}"
          username : "{{ SN_USERNAME }}"
          password : "{{ SN_PASSWORD }}"
      register: oauth_return_token

    - name: display token info
      debug: 
        msg: " {{ oauth_return_token.json.access_token }} "

    - name: close SR task
      ansible.builtin.uri:
        url: "{{ SN_HOST }}/api/abb2/fulfilment_automation/updateTask/TASK8611047"
        method: PUT
        headers:
          Content-Type : application/json
          Accept : application/json
          Authorization : "Bearer {{ oauth_return_token.json.access_token }}"
          connection : keep-alive
          Accept-Encoding : gzip, deflate, br
        body_format: json
        body: '{"work_notes": "close notes from Ansible"}'
      register: SR_task_closure

