---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Grab token using OAuth
      ansible.builtin.uri:
        url: "{{ SN_HOST }}/oauth_token.do"
        method: POST
        body_format: form-urlencoded
        return_content: true
        body:
          grant_type : password
          client_id : "{{ SN_CLIENT_ID }}"
          client_secret : "{{ SN_CLIENT_SECERT }}"
          username : "{{ SN_USERNAME }}"
          password : "{{ SN_PASSWORD }}"
      register: oauth_return_token

    - name: display token info
      debug: 
        msg: " {{ oauth_return_token.json.access_token }} "

    # - name: Ansible take SR task
    #   ansible.builtin.uri:
    #     url: "{{ SN_HOST }}/api/abb2/fulfilment_automation/updateTask/{{ sn_task_number }}"
    #     method: PUT
    #     headers:
    #       Content-Type : application/json
    #       Accept : application/json
    #       Authorization : "Bearer {{ oauth_return_token.json.access_token }}"
    #     body_format: json
    #     body: 
    #       assigned_to: int_ansible
    #       state: WORK_IN_PROGRESS
    #       work_notes: "Automation is in progress"
    #   register: SR_task_wip  

    - name: Ansible reassign this task to wintel manual queue
      ansible.builtin.uri:
        url: "{{ SN_HOST }}/api/abb2/fulfilment_automation/updateTask/{{ sn_task_number }}"
        method: PUT
        headers:
          Content-Type : application/json
          Accept : application/json
          Authorization : "Bearer {{ oauth_return_token.json.access_token }}"
        body_format: json
        body: 
          assignment_group: "{{ wintel_support_group }}"
          assigned_to : ""
          close_code: "failed"
          state: WORK_IN_PROGRESS
          work_notes: "Error has been encountered during the automation run, please check manually"
          closure_notes: "Automation job is incomplete due to error encountered, please check maually"
      register: SR_task_reassign

    - name: display the details
      debug: 
        msg: " {{ SR_task_reassign }} "


