---
- name: Get variable list from ServiceNow request
  hosts: localhost
  vars:
    sys_id: "{{ request_number }}"
    username: "{{ servicenow_username }}"
    password: "{{ servicenow_password }}"
    instance: "{{ servicenow_instance }}"
  tasks:
    - name: Fetch Task Details
      uri:
        url: "{{ instance }}/api/now/table/sc_task/{{ sys_id }}"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        status_code: 200
        body_format: json
        return_content: yes
        headers:
          Accept: "application/json"
      register: task_details

    - debug:
        msg: "{{ task_details.json }}"
