---
- name: Manage and validate local group members on Windows servers
  hosts: all
  gather_facts: no
  collections:
    - ansible.windows

  tasks:

  - name: Add members to Administrators group
    win_group:
      name: Administrators
      members:
        - 'abb\HPAM-TCS-Backup-Servers-Admins-RW'
        - 'abb\HPAM-TCS-Wintel-Servers-Admins-RW'
        - 'abb\HPAM-TCS-CC-Servers-Admins-RW'
        - 'abb\xeqgscan'
        - 'europe\abbitim-abb_dc1_admin_access_windows'
        - 'europe\abbitim-abb_dc1_rdusers_access_windows'
        - 'europe\tcsitim-tcsch_windows_team'
        - 'europe\tcs-eur-win-srv'
        - 'ABB\GLB-ABBCMDB'
        - 'ABB\TCS-PAM-Scan'
    ignore_errors: yes

  - name: Log message for Administrators group addition
    debug:
      msg: "Local Administrators added"

  - name: Fetch and validate a member in Administrators group
    win_shell: |
      if (Get-LocalGroupMember -Group "Administrators" | Where-Object { $_.Name -eq 'abb\HPAM-TCS-Backup-Servers-Admins-RW' }) {
        Write-Output "Validation: Member 'abb\HPAM-TCS-Backup-Servers-Admins-RW' is present in Administrators group."
      } else {
        Write-Output "Validation: Member 'abb\HPAM-TCS-Backup-Servers-Admins-RW' is not present in Administrators group."
      }
    register: admin_validation

  - name: Display validation result for Administrators group
    debug:
      msg: "{{ admin_validation.stdout }}"

  - name: Add member to Remote Desktop Users group
    win_group:
      name: Remote Desktop Users
      members:
        - 'europe\abbitim-abb_dc1_rdusers_access_windows'
    ignore_errors: yes

  - name: Log message for Remote Desktop Users group addition
    debug:
      msg: "Remote Desktop Users added"

  - name: Fetch and validate a member in Remote Desktop Users group
    win_shell: |
      if (Get-LocalGroupMember -Group "Remote Desktop Users" | Where-Object { $_.Name -eq 'europe\abbitim-abb_dc1_rdusers_access_windows' }) {
        Write-Output "Validation: Member 'europe\abbitim-abb_dc1_rdusers_access_windows' is present in Remote Desktop Users group."
      } else {
        Write-Output "Validation: Member 'europe\abbitim-abb_dc1_rdusers_access_windows' is not present in Remote Desktop Users group."
      }
    register: rdusers_validation

  - name: Display validation result for Remote Desktop Users group
    debug:
      msg: "{{ rdusers_validation.stdout }}"
