- name: Add Additional Disks to Windows VM in vCenter
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Prepare disk list with unit numbers
      set_fact:
        disks_with_unit_numbers: "{{ mrvs_variables | map('combine', {'unit_number': ansible_loop.index0}) | list }}"
      loop: "{{ mrvs_variables }}"
      loop_control:
        extended: true

    - name: Add additional disks to the VM
      community.vmware.vmware_guest_disk:
        hostname: "{{ Vcenter_Name }}"
        validate_certs: no
        datacenter: "{{ Vmware_datacenter }}"
        name: "{{ VMware_VM_name }}"
        disk: "{{ disks_with_unit_numbers | map(attribute='disk') | list }}"
      vars:
        disk: >
          {
            'size_gb': '{{ item.disk_size_gb }}',
            'type': 'thin',
            'state': 'present',
            'scsi_controller': 0,
            'unit_number': '{{ item.unit_number }}'
          }
      loop: "{{ disks_with_unit_numbers }}"

    - debug:
        var: disks_with_unit_numbers

    - debug:
        var: additional_disk_results
