---
- name: Windows post provisioning  
#  hosts: "{{ VMware_VM_IP_address }}"
  hosts: all
  gather_facts: no
  collections:
    - ansible.windows
    - community.vmware
    - community.windows
  tasks:
    - name: Get list of unallocated disks
      win_shell: |
        Get-Disk | Where-Object PartitionStyle -eq 'RAW' | Select-Object -ExpandProperty Number
      register: unallocated_disks

    - name: Check if there are enough unallocated disks
      fail:
        msg: "Not enough unallocated disks available. Found: {{ unallocated_disks.stdout_lines | length }}. Required: {{ mrvs_variables | length }}."
      when: unallocated_disks.stdout_lines | length < mrvs_variables | length

    - name: Create a list of disks to format
      set_fact:
        disks_to_format: >-
          [{% for disk in mrvs_variables %}
            { "disk_number": "{{ unallocated_disks.stdout_lines[loop.index0] }}", "disk_label": "{{ disk.disk_label }}", "disk_size_gb": {{ disk.disk_size_gb }} }{% if not loop.last %}, {% endif %}{% endfor %}]

    - name: Format and label each disk
      win_shell: |
        $disk_number = {{ item.disk_number }}
        $disk_label = "{{ item.disk_label }}"
        $disk_size = {{ item.disk_size_gb }} * 1GB  # Convert GB to bytes

        # Initialize and format the disk
        Initialize-Disk -Number $disk_number -PartitionStyle MBR -PassThru |
        New-Partition -AssignDriveLetter -Size $disk_size | 
        Format-Volume -FileSystem NTFS -NewFileSystemLabel $disk_label -Confirm:$false
      loop: "{{ disks_to_format }}"
