---
- name: Add Additional Disks to Windows VM in vCenter
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Initialize unit_number
      set_fact:
        unit_number: 0

    - name: Add additional disks to the VM
      community.vmware.vmware_guest_disk:
        hostname: "{{ Vcenter_Name }}"
        datacenter: "{{ Vmware_datacenter }}"
        validate_certs: no
        name: "{{ VMware_VM_name }}"
        disk:
          - size_gb: "{{ item.disk_size_gb }}"
            type: thin
            state: present
            scsi_controller: 0  
            unit_number: "{{ unit_number }}"
      with_items: "{{ mrvs_variables }}"
      register: additional_disk_results

      # Increment unit_number for the next iteration
      post_tasks:
        - set_fact:
            unit_number: "{{ unit_number + 1 }}"

    - debug:
        var: additional_disk_results
