---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Grab token using OAuth
      ansible.builtin.uri:
        url: "{{ SN_HOST }}/oauth_token.do"
        method: POST
        body_format: form-urlencoded
        return_content: true
        body:
          grant_type : password
          client_id : "{{ SN_CLIENT_ID }}"
          client_secret : "{{ SN_CLIENT_SECERT }}"
          username : "{{ SN_USERNAME }}"
          password : "{{ SN_PASSWORD }}"
      register: oauth_return_token

    - name: Ansible update the state as closed incomplete if SL task fails
      ansible.builtin.uri:
        url: "{{ SN_HOST }}/api/abb2/fulfilment_automation/updateTask/{{ sn_task_number }}"
        method: PUT
        headers:
          Content-Type : application/json
          Accept : application/json
          Authorization : "Bearer {{ oauth_return_token.json.access_token }}"
        body_format: json
        body: 
          state: CLOSED_IN_COMPLETE
          work_notes: "Error has been encountered during the automation run. \nError Detail: {{ Science_Logic_message }}. \nPlease deploy the change manually"
          closure_notes: "Automation job is incomplete"
      when: Science_Logic_message is defined
      register: SR_SL_task_close_incomplete

    - name: Ansible update the state as closed incomplete if cmdb task fails
      ansible.builtin.uri:
        url: "{{ SN_HOST }}/api/abb2/fulfilment_automation/updateTask/{{ sn_task_number }}"
        method: PUT
        headers:
          Content-Type : application/json
          Accept : application/json
          Authorization : "Bearer {{ oauth_return_token.json.access_token }}"
        body_format: json
        body: 
          state: CLOSED_IN_COMPLETE
          work_notes: "Error has been encountered during the automation run. \nError Detail: {{ cmdb_failed_message }}. \nPlease deploy the change manually"
          closure_notes: "Automation job is incomplete"
      when: cmdb_failed_message is defined
      register: SR_cmdb_task_close_incomplete
      
