---
- name: Windows post provisioning  
#  hosts: "{{ VMware_VM_IP_address }}"
  hosts: xf-s-aapwin04t
  gather_facts: no
  collections:
    - ansible.windows
    - community.vmware
    - community.windows
  tasks:
    - name: Find files and directories under C:\Temp
      win_find:
        paths: C:\Temp
        recurse: yes
      register: temp_contents

    - name: Display the contents of C:\Temp
      debug:
        var: temp_contents.files
        verbosity: 2

    - name: Display the directories under C:\Temp
      debug:
        var: temp_contents.directories
        verbosity: 2
    
