- name: VM from template
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    template_password: P@ssw0rd123456
    notes: Ansible Test
    dumpfacts: False
  tasks:
    - name: Pre-calculate unit numbers for additional disks
      set_fact:
        disk_sizes: "{{ mrvs_variables | map(attribute='disk_size_gb') | list }}"
        additional_disks: "{{ disk_sizes | zip_longest([], fillvalue={}) | map('combine', {'unit_number': range(1, len(disk_sizes) + 1)}) | list }}"

    - name: Pre-calculate complete disk list
      set_fact:
        disk_list: 
          [
            {"size_gb": "{{ VMware_VM_disk_size }}", "type": "thin", "datastore": "{{ Vmware_datastore }}"}
          ]

    - name: Add additional disks to the list
      set_fact:
        disk_list: "{{ disk_list + [{'size_gb': item.disk_size_gb, 'type': 'thin', 'datastore': Vmware_datastore, 'unit_number': item.unit_number}] }}"
      loop: "{{ additional_disks }}"
      loop_control:
        label: "{{ item.disk_label }}"

    - name: Create VM from template
      community.vmware.vmware_guest:
        validate_certs: False
        datacenter: "{{ Vmware_datacenter }}"
        cluster: "{{ Vmware_cluster }}"
        folder: "{{ VMware_VM_folder }}"
        name: "{{ VMware_VM_name }}"
        template: "{{ VMware_VM_template }}"
        disk: "{{ disk_list }}"
        networks:
          - name: "{{ Vmware_networks }}"
            ip: "{{ VMware_VM_IP_address }}"
            netmask: "{{ Vmware_Subnet_netmask }}"
            gateway: "{{ Vmware_Subnet_gateway }}"
            dns_servers:
              - "{{ Vmware_DNS1 }}"
              - "{{ Vmware_DNS2 }}"
              - "{{ Vmware_DNS3 }}"
            domain: "{{ Vmware_DNS_Suffix }}"
        hardware:
          num_cpus: "{{ Vmware_VM_CPU }}"
          memory_mb: "{{ Vmware_VM_mem }}"
        customization:
          password: "{{ template_password }}"
          runonce:
            - cmd /c echo New-NetFirewallRule -DisplayName "WinRM 5985" -Direction Inbound -LocalPort 5985 -Protocol TCP -RemoteAddress Any -Action Allow > C:\enable_winrm.ps1
            - powershell.exe -ExecutionPolicy Unrestricted -File C:\enable_winrm.ps1 -ForceNewSSLCert -EnableCredSSP
        wait_for_customization: yes
        wait_for_ip_address: True
        state: present
      register: newvm
