---
- name: Manage Local Administrators and Remote Desktop Users
  hosts: all
  gather_facts: no
  collections:
    - ansible.windows
  tasks:
    - name: Add members to Administrators group
      win_group_membership:
        name: Administrators
        members:
          - 'abb\HPAM-TCS-Backup-Servers-Admins-RW'
          - 'abb\HPAM-TCS-Wintel-Servers-Admins-RW'
          - 'abb\HPAM-TCS-CC-Servers-Admins-RW'
          - 'abb\xeqgscan'
          - 'europe\abbitim-abb_dc1_admin_access_windows'
          - 'europe\abbitim-abb_dc1_rdusers_access_windows'
          - 'europe\tcsitim-tcsch_windows_team'
          - 'europe\tcs-eur-win-srv'
          - 'ABB\GLB-ABBCMDB'
          - 'ABB\TCS-PAM-Scan'
      register: admin_group_result

    - name: Log admin group changes
      debug:
        msg: "Local Administrators added: {{ admin_group_result.changed }}"

    - name: Add members to Remote Desktop Users group
      win_group_membership:
        name: "Remote Desktop Users"
        members:
          - 'europe\abbitim-abb_dc1_rdusers_access_windows'
      register: rd_group_result

    - name: Log remote desktop users group changes
      debug:
        msg: "Remote Desktop Users added: {{ rd_group_result.changed }}"

    - name: Get members of the Administrators group
      win_command: net localgroup Administrators
      register: admin_members

    - name: Display Administrators group members
      debug:
        var: admin_members.stdout_lines

    - name: Get members of the Remote Desktop Users group
      win_command: net localgroup "Remote Desktop Users"
      register: rd_members

    - name: Display Remote Desktop Users group members
      debug:
        var: rd_members.stdout_lines
