---
- name: Gather and sort vCenter datastores
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Gather vCenter datastores
    community.vmware.vmware_datastore_info:
    register: datastores

  - name: List the datastores
    debug:
      var: datastores

  - name: Filter datastores by name
    set_fact:
      filtered_datastores: "{{ datastores.datastores | selectattr('name', 'contains', 'DMZ') }}"

 # - name: Display datastores with free space
 #   debug:
 #     msg: "Datastore {{ item.name }} has {{ item.freeSpace }} bytes of free space."
 #   loop: "{{ sorted_datastores }}"
