---
- name: Resize CPU for VM in vCenter
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Get the VM inventory - before changes
      register: pre_result
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
        - "{{ variables.server }}"

    - name: Set Pre CPU core variable
      set_fact:
        requested_cpu_cores: "{{ variables.CPU_Cores | regex_replace(' Core', '') | int }}"
        current_cpu_cores: "{{ pre_result.value[0].cpu_count | int }}"

    - name: Set CPU core increase variable value
      set_fact:
        cpu_cores_increase: "{{ (current_cpu_cores | int) + (requested_cpu_cores | int) }}"
      when: variables.Action_Required == "Increase"

    - name: Set CPU core decrease variable value
      set_fact:
        cpu_cores_decrease: "{{ (current_cpu_cores | int) - (requested_cpu_cores | int) }}"
      when: variables.Action_Required == "Decrease"

    - name: Check if CPU decrease would result in 0 or less CPUs
      fail:
        msg: "Cannot decrease CPU count to 0 or less"
      when: variables.Action_Required == 'Decrease' and (cpu_cores_decrease | int) <= 0

    - name: Power OFF the VM
      community.vmware.vmware_guest_powerstate:
        name: "{{ variables.server }}"
        state: powered-off
      ignore_errors: yes

    - name: Wait until virtual machine offline
      vmware.vmware_rest.vcenter_vm_tools_info:
        vm: '{{ pre_result.value[0].vm }}'
      register: vm_tools_info
      until:
      - vm_tools_info is not failed
      - vm_tools_info.value.run_state == "NOT_RUNNING"
      retries: 60
      delay: 5

    - name: Increase the CPU size on the VM
      community.vmware.vmware_guest:
        name: "{{ variables.server }}"
        hardware:
          num_cpus: "{{ cpu_cores_increase }}"
          num_cpu_cores_per_socket: "{{ cpu_cores_increase }}"
        state: present
      when: variables.Action_Required == 'Increase'
      register: cpu_result_increase

    - name: Decrease the CPU size on the VM
      community.vmware.vmware_guest:
        name: "{{ variables.server }}"
        hardware:
          num_cpus: "{{ cpu_cores_decrease }}"
          num_cpu_cores_per_socket: "{{ cpu_cores_decrease }}"
        state: present
      when: variables.Action_Required == 'Decrease'
      register: cpu_result_decrease

    - name: Power ON the VM
      community.vmware.vmware_guest_powerstate:
        name: "{{ variables.server }}"
        state: powered-on

    - name: Wait until my VM is ready
      vmware.vmware_rest.vcenter_vm_tools_info:
        vm: '{{ pre_result.value[0].vm }}'
      register: vm_tools_info
      until:
      - vm_tools_info is not failed
      - vm_tools_info.value.run_state == "RUNNING"
      retries: 60
      delay: 5

    - name: Get the VM inventory - post changes
      register: post_result
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
        - "{{ variables.server }}"

    - name: Set Post VM Status
      set_fact:
        resized_cpu_count: "{{ post_result.value[0].cpu_count | int }}"
        post_server_state: "{{ post_result.value[0].power_state }}"
        
    - set_stats:
        data:
          CPU_Core_before: "{{ current_cpu_cores }}"  
          CPU_Core_after: "{{ resized_cpu_count }}" 
          vm_power_state: "{{ post_server_state }}" 
          catalog_item: CPU
        
