---
- name: Shutdown and reboot using SNOW variable
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get VM info
      community.vmware.vmware_vm_info:
         vm_name: "{{ vm_name }}"
      register: vm_info

    - debug: 
        var: vm_info

    - name: Check if VM is powered on
      debug:
        msg: "VM {{ vm_name }} is {{ vm_info.virtual_machines[0].power_state }}"
      when: vm_info.virtual_machines | length > 0 and vm_info.virtual_machines[0].power_state == 'poweredOn'

    - name: Check if VM is powered off
      debug:
        msg: "VM {{ vm_name }} is already {{ vm_info.virtual_machines[0].power_state }}"
      when: vm_info.virtual_machines | length > 0 and vm_info.virtual_machines[0].power_state == 'poweredOff'


    - name: Set the state of the virtual machine to poweron
      community.vmware.vmware_guest_powerstate:
         name: "{{ vm_name }}"
         state: powered-on
      register: poweron
      when: vm_info.virtual_machines | length > 0 and vm_info.virtual_machines[0].power_state == 'poweredOff'

    - debug:
        var: poweron

 #   - name: Wait for the virtual machine to be powered on
  #    community.vmware.vmware_guest_powerstate:
  #       name: "{{ vm_name }}"
  #    register: vm_info_poweredon
  #    until: vm_info_poweredon.virtual_machines[0].power_state == 'poweredOn'
  #    retries: 10
   #   delay: 30
   #   when: poweron is defined and poweron.guest.power_state == 'poweredOn'
   
