---
- name: Resize memory and CPU for VM in vCenter
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Set cpu_cores variable
      set_fact:
         cpu_cores: "{{ variables.CPU_Cores | regex_replace(' Core', '') | int }}"

    - name: Power off the VM
      vmware_guest_powerstate:
        name: "{{ variables.server }}"
        state: powered-off
      ignore_errors: yes

    - name: Wait for 30 seconds for VM to powered down
      wait_for:
        timeout: 5
      delegate_to: localhost

    - name: Edit VM Settings
      vmware_guest:
        name: "{{ variables.server }}"
        hardware:
          num_cpus: "{{ cpu_cores }}"
          num_cpu_cores_per_socket: "{{ cpu_cores }}"               
        state: present
      register: cpu_result

    - name: Power on the VM
      vmware_guest_powerstate:
        name: "{{ variables.server }}"
        state: powered-on
    
    - name: Look up the VM inventory
      register: search_result
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
        - "{{ variables.server }}"

    - name: Collect information about a specific VM
      vmware.vmware_rest.vcenter_vm_info:
         vm: '{{ search_result.value[0].vm }}'
      register: win_vm_info
      
    - name: Fail if CPU resize did not happen
      fail:
        msg: "CPU is not resized on the server"
      when: not cpu_result.changed
