---
- name: Reboot using SNOW variable
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Shutdown the VM
      community.vmware.vmware_guest_powerstate:
         name: "{{ vm_name }}"
         state: shutdown-guest
