---
- name: Shutdown the VM using SNOW variable
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Shutdown the VM
      community.vmware.vmware_guest_powerstate:
         name: xf-s-aapwin04t
    #     name: "{{ variables.server }}"
         state: shutdown-guest
