---
- name: Resize memory and CPU for VM in vCenter
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Power off the VM
      vmware_guest_powerstate:
        name: "{{ variables.server }}"
        state: powered-off
      ignore_errors: yes

    - name: Wait for 30 seconds for VM to powered down
      wait_for:
        timeout: 10
      delegate_to: localhost

    - name: Convert RAM to MB
      set_fact:
         ram_in_mb: "{{ variables.ram_in_gb | int * 1024 }}"

    - name: Edit VM Settings
      vmware_guest:
        name: "{{ variables.server }}"
        hardware:
          memory_mb: "{{ ram_in_mb }}"
        state: present
      register: mem_result

    - name: Power on the VM
      vmware_guest_powerstate:
        name: "{{ variables.server }}"
        state: powered-on
        
    - name: Fail when there is mem not resized
      fail:
        msg: "RAM is not resized on the server"
      when: not mem_result.changed
