---
- name: Reboot using SNOW variable
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Gather some info from a guest using the vSphere API output schema
      community.vmware.vmware_guest_info:
        name: xf-s-aapwin04t
        datacenter: XF-COMP
        schema: "vsphere"
        properties: ["summary.runtime.bootTime"]
      register: boot_time_info

    - debug: 
        var: boot_time_info

    - name: Get the VM inventory - before changes
      register: pre_result
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
        - xf-s-aapwin04t

    - debug: var=vm_guest_info

    # - name: Reboot the virtual machine
    #   community.vmware.vmware_guest_powerstate:
    #      name: "{{ variables.server }}"
    #      state: reboot-guest
    #   register: reboot_result

    # - name: Fail if VM reboot is not happen
    #   fail:
    #     msg: "VM is already in shutdown state"
    #   when: not reboot_result.changed
      
    # - name: wait for task complete
    #   wait_for:
    #     timeout: 30
