---
- name: Resize memory and CPU for VM in vCenter
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Power off the VM
      vmware_guest_powerstate:
        name: "{{ variables.server }}"
        state: powered-off

    - name: Wait for 30 seconds for VM to powered down
      wait_for:
        timeout: 10
      delegate_to: localhost

    - name: Edit VM Settings
      vmware_guest:
        name: "{{ vm_name }}"
        hardware:
          num_cpus: "{{ variables.server }}"
        state: present

    - name: Power on the VM
      vmware_guest_powerstate:
        name: "{{ vm_name }}"
        state: powered-on
