---
- name: Resize memory VM in vCenter
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Look up the VM inventory
      register: search_result
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
        - "{{ variables.server }}"
