---
- name: Shutdown the VM
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get the VM inventory - before changes
      register: pre_result
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
        - "{{ variables.server }}"
  
    - name: Check VM power state
      community.vmware.vmware_vm_info:
         vm_name: "{{ variables.server }}"
      register: vm_power_state

    - name: Fail if server is already shut down or shutdown task did not change state
      fail:
         msg: "Server is already shut down or shutdown task did not change state."
      when: vm_power_state.virtual_machines | length > 0 and vm_power_state.virtual_machines[0].power_state == 'poweredOff'
      
    - name: Shutdown the VM
      community.vmware.vmware_guest_powerstate:
         name: "{{ variables.server }}"
         state: shutdown-guest
      when: vm_power_state.virtual_machines | length > 0 and vm_power_state.virtual_machines[0].power_state == 'poweredOn'
        
    - name: Wait until virtual machine offline
      vmware.vmware_rest.vcenter_vm_tools_info:
        vm: '{{ pre_result.value[0].vm }}'
      register: vm_tools_info
      until:
      - vm_tools_info is not failed
      - vm_tools_info.value.run_state == "NOT_RUNNING"
      retries: 60
      delay: 5

    - name: Get the VM inventory - after changes
      register: post_result
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
        - "{{ variables.server }}"

   - name: Set Post VM Status
     set_fact:
        pre_server_state: "{{ pre_result.value[0].power_state }}"
        post_server_state: "{{ post_result.value[0].power_state }}"

   - set_stats:
        data:
          vm_pre_power_state: "{{ pre_server_state }}" 
          vm_post_power_state: "{{ post_server_state }}" 
          catalog_item: Shutdown
