---
# create a new VM from a template

- name: VM from template
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    template_password: P@ssw0rd123456
    notes: Ansible Test
    dumpfacts: False
  tasks:
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        datacenter: "{{ Vmware_datacenter }}"
        cluster: "{{ Vmware_cluster }}"
        folder: "{{ VMware_VM_folder }}"
        name: "{{ VMware_VM_name }}"
        template: "{{ VMware_VM_template }}"
        disk:
          - size_gb: "{{ VMware_VM_disk_size }}"
            type: thin
            datastore: "{{ Vmware_datastore }}"
        networks:
        - name: "{{ Vmware_networks }}"
          ip: "{{ VMware_VM_IP_address }}"
          netmask: "{{ Vmware_Subnet_netmask }}"
          gateway: "{{ Vmware_Subnet_gateway }}"
          domain: "{{ Vmware_test_DNS_suffix }}"
          dns_servers:
          - "{{ Vmware_DNS1 }}"
          - "{{ Vmware_DNS2 }}"
          - "{{ Vmware_DNS3 }}"
        hardware:
          num_cpus: "{{ Vmware_VM_CPU }}"
          memory_mb: "{{ Vmware_VM_mem }}"
        customization:
          password: "{{ template_password }}"
      # This powershell script is required for cross vlan WinRM to run the next tasks - Once playbook complete remove the firewall rule if needed
          runonce:
           - cmd /c echo New-NetFirewallRule -DisplayName "WinRM 5985" -Direction Inbound -LocalPort 5985 -Protocol TCP -RemoteAddress Any -Action Allow > C:\enable_winrm.ps1
           - powershell.exe -ExecutionPolicy Unrestricted -File C:\enable_winrm.ps1 -ForceNewSSLCert -EnableCredSSP
        wait_for_customization: yes
        wait_for_ip_address: True
        state: present
      register: newvm
