---
- name: Gather VM facts
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Gather VM facts
    community.vmware.vmware_vm_info:
      name: "{{ vm_name }}"
    register: vm_facts

 # - name: Display CPU core count
  #  debug:
   #   var: vm_facts.guest.numCPU
