---
- name: Resize CPU for VM in vCenter
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Look up the VM inventory
      register: search_result
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
        - "{{ variables.server }}"

    - name: Set cpu_cores variable
      set_fact:
        cpu_cores: "{{ variables.CPU_Cores | regex_replace(' Core', '') | int }}"
        current_cpu_count: "{{ search_result.value[0].cpu_count | int }}"

    - name: Set CPU core increase variable value
      set_fact:
        cpu_cores_increase: "{{ (current_cpu_count | int) + (cpu_cores | int) }}"
      when: variables.Action_Required == "Increase"

    - name: Set CPU core decrease variable value
      set_fact:
        cpu_cores_decrease: "{{ (current_cpu_count | int) - (cpu_cores | int) }}"
      when: variables.Action_Required == "Decrease"

    - name: Check if CPU decrease would result in 0 or less CPUs
      fail:
        msg: "Cannot decrease CPU count to 0 or less"
      when: variables.Action_Required == 'Decrease' and (cpu_cores_decrease | int) <= 0

    - name: Power off the VM
      vmware_guest_powerstate:
        name: "{{ variables.server }}"
        state: powered-off
      ignore_errors: yes

    - name: Wait for 30 seconds for VM to powered down
      wait_for:
        timeout: 5
      delegate_to: localhost

    - name: Increase the CPU size on the VM
      vmware_guest:
        name: "{{ variables.server }}"
        hardware:
          num_cpus: "{{ cpu_cores_increase }}"
          num_cpu_cores_per_socket: "{{ cpu_cores_increase }}"
        state: present
      when: variables.Action_Required == 'Increase'
      register: cpu_result_increase

    - name: Decrease the CPU size on the VM
      vmware_guest:
        name: "{{ variables.server }}"
        hardware:
          num_cpus: "{{ cpu_cores_decrease }}"
          num_cpu_cores_per_socket: "{{ cpu_cores_decrease }}"
        state: present
      when: variables.Action_Required == 'Decrease'
      register: cpu_result_decrease

    - name: Power on the VM
      vmware_guest_powerstate:
        name: "{{ variables.server }}"
        state: powered-on
    
    - name: Collect information about a specific VM
      vmware.vmware_rest.vcenter_vm_info:
         vm: '{{ search_result.value[0].vm }}'
      register: win_vm_info
      
