---
- name: Reboot the VM
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Extract datacenter name
      ansible.builtin.set_fact:
        Vcenter_Name: "{{ hostvars[variables.server]['tag_category']['vcenter'] | first }}"
        
    - name: Get the VM inventory - before changes
      register: pre_result
      vmware.vmware_rest.vcenter_vm_info:
        vcenter_hostname: '{{ Vcenter_Name }}'
        vcenter_username: '{{ VMWARE_USERNAME }}'
        vcenter_password: '{{ VMWARE_PASSWORD }}'
        vcenter_validate_certs: false
        filter_names:
        - "{{ variables.server }}"

    - name: Gather VM information
      community.vmware.vmware_vm_info:
         hostname: '{{ Vcenter_Name }}'
         username: '{{ VMWARE_USERNAME }}'
         password: '{{ VMWARE_PASSWORD }}'
         vm_name: "{{ variables.server }}"
         validate_certs: false
         vm_name: "{{ variables.server }}"
      register: vm_info

    - ansible.builtin.debug: var=vm_info
        
    - name: Filter datacenter value
      ansible.builtin.set_fact:
        datacenter_value: "{{ vm_info.virtual_machines[0].datacenter }}"
       
    - name: Fetch the VM time before reboot
      community.vmware.vmware_guest_info:
        hostname: '{{ Vcenter_Name }}'
        username: '{{ VMWARE_USERNAME }}'
        password: '{{ VMWARE_PASSWORD }}'
        validate_certs: false
        name: "{{ variables.server }}"
        datacenter: "{{ datacenter_value }}"
        schema: "vsphere"
        properties: ["summary.runtime.bootTime"]
      register: time_before_boot

    - ansible.builtin.debug: var=time_before_boot

    - name: Set last reboot time 
      ansible.builtin.set_fact:
        last_boot_time: "{{ time_before_boot.instance.summary.runtime.bootTime }}"
       
    - name: Reboot the virtual machine
      community.vmware.vmware_guest_powerstate:
         hostname: '{{ Vcenter_Name }}'
         username: '{{ VMWARE_USERNAME }}'
         password: '{{ VMWARE_PASSWORD }}'
         name: "{{ variables.server }}"
         validate_certs: false
         state: reboot-guest
      register: reboot_result

    - name: Fail if VM reboot is not happen
      ansible.builtin.fail:
        msg: "VM is already in shutdown state, Please check the reason manually"
      when: not reboot_result.changed

    - name: wait for reboot to happen
      ansible.builtin.wait_for:
         timeout: 30

    - name: Wait until my VM is ready
      vmware.vmware_rest.vcenter_vm_tools_info:
        vcenter_hostname: '{{ Vcenter_Name }}'
        vcenter_username: '{{ VMWARE_USERNAME }}'
        vcenter_password: '{{ VMWARE_PASSWORD }}'
        vcenter_validate_certs: false
        vm: '{{ pre_result.value[0].vm }}'
      register: vm_tools_info
      until:
      - vm_tools_info is not failed
      - vm_tools_info.value.run_state == "RUNNING"
      retries: 60
      delay: 5

    - name: Fetch the VM time after reboot
      community.vmware.vmware_guest_info:
        hostname: '{{ Vcenter_Name }}'
        username: '{{ VMWARE_USERNAME }}'
        password: '{{ VMWARE_PASSWORD }}'
        validate_certs: false
        name: "{{ variables.server }}"
        datacenter: "{{ datacenter_value }}"
        schema: "vsphere"
        properties: ["summary.runtime.bootTime"]
      register: time_after_boot

    - ansible.builtin.debug: var=time_after_boot

    - name: Set latest reboot time
      ansible.builtin.set_fact:
        final_boot_time: "{{ time_after_boot.instance.summary.runtime.bootTime }}"
    
    - name: Get the VM inventory - post changes
      register: post_result
      vmware.vmware_rest.vcenter_vm_info:
        vcenter_hostname: '{{ Vcenter_Name }}'
        vcenter_username: '{{ VMWARE_USERNAME }}'
        vcenter_password: '{{ VMWARE_PASSWORD }}'
        vcenter_validate_certs: false
        filter_names:
        - "{{ variables.server }}"
      
    - name: Set Post VM Status
      ansible.builtin.set_fact:
        post_server_state: "{{ post_result.value[0].power_state }}"
        
    - ansible.builtin.set_stats:
        data:
          time_before_reboot: "{{ last_boot_time }}"
          time_after_reboot: "{{ final_boot_time }}"
          vm_power_state: "{{ post_server_state }}" 
          catalog_item: Reboot
      
