---
- name: Reboot using SNOW variable
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Reboot the virtual machine
      community.vmware.vmware_guest_powerstate:
         name: xf-s-aapwin04t
    #     name: "{{ variables.server }}"
         state: reboot-guest
      
    - name: wait for task complete
      wait_for:
        timeout: 45
