---
- name: Shutdown the VM using SNOW variable
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check VM power state
      community.vmware.vmware_vm_info:
         vm_name: xf-s-aapwin04t
      register: vm_power_state
#      ignore_errors: yes
      
    - name: Shutdown the VM
      community.vmware.vmware_guest_powerstate:
         name: xf-s-aapwin04t
    #     name: "{{ variables.server }}"
         state: shutdown-guest
      when: vm_power_state.virtual_machines | length > 0 and vm_power_state.virtual_machines[0].power_state == 'poweredOn'
