---
- name: Gather VM facts
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Collect information about a specific VM
    vmware.vmware_rest.vcenter_vm_info:
      vm: "{{ vm_name }}"
    register: win_vm_info

 # - name: Display CPU core count
  #  debug:
   #   var: vm_facts.guest.numCPU
