- name: Convert MB to GB
  hosts: localhost
  gather_facts: no

  vars:
    volume_size_mb: 1024

  tasks:
  - name: Convert MB to GB
    set_fact:
      volume_size_gb: "{{ volume_size_mb | human_readable(unit='G') }}"
    register: convertedsize

  - name: Print the result
    debug:
      msg: "Volume size in GB: {{ volume_size_gb }}"
