---
- name: Convert RAM from GB to MB
  hosts: localhost
  gather_facts: no

#  vars:
 #   ram_in_gb: 2

  tasks:
#  - name: Convert RAM to MB
#    set_fact:
#      ram_size: "{{ ram_in_gb * 1024 }}"

  - name: Convert RAM to MB
    set_fact:
        ram_in_mb: "{{ variables.ram_in_gb * 1024 }}"

  - name: Display RAM size in MB
    debug:
      var: ram_in_mb
