---
- name: Resize memory VM in vCenter
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Look up the VM inventory
      register: search_result
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
        - "{{ variables.server }}"

    - name: Set memory variable
      set_fact:
        memory_request: "{{ variables.Memory_Size | regex_replace(' GB', '') | int }}"
        memory_size: "{{ search_result.value[0].memory_size_MiB | int }}"

    - name: Convert RAM to MB
      set_fact:
         ram_in_mb: "{{ (memory_request | int) * 1024 }}"

    - name: Set memory increase variable
      set_fact:
        memory_increase: "{{ (memory_size | int) + (ram_in_mb | int) }}"
      when: variables.Action_Required == "Increase"

    - name: Set cpu_cores_decrease variable when Action_Required is Decrease
      set_fact:
        memory_decrease: "{{ (memory_size | int) - (ram_in_mb | int) }}"
      when: variables.Action_Required == "Decrease"

    - name: Check if Memory decrease would result in 0 or less Memory
      fail:
        msg: "Cannot decrease memory size to 1GB or less, please check manually"
      when: variables.Action_Required == 'Decrease' and (memory_decrease | int) <= 1024
