---
- hosts: localhost
  connection: local
  vars:
     nios_provider:
        host: "{{ INFOBLOX_HOST }}"
        username: "{{ INFOBLOX_USERNAME }}"
        password: "{{ INFOBLOX_PASSWORD }}"
          
  tasks:

    - name: Configure an A record
      infoblox.nios_modules.nios_a_record:
        name: "{{a_record_name}}"
        ipv4: "{{a_record_ip}}"
        state: present
        provider: "{{nios_provider}}"

    - name: Create a PTR Record
      infoblox.nios_modules.nios_ptr_record:
        ipv4: 10.17.113.103
        ptrdname: 103.113.17.10.in-addr.arpa
        state: present
        provider: "{{nios_provider}}"
    
        
    - name: Get the a & ptr record of a host
      ansible.builtin.set_fact:
        host_list: "{{ lookup('infoblox.nios_modules.nios_lookup', 'record:a', filter={'name': 'xf-s-aaptest04t.abb.lab'}, provider=nios_provider) }}"
    - name: Display the host a record
      ansible.builtin.debug:
        msg: "{{ host_list }}"
