---
- hosts: "{{ VM_hosts }}"
  gather_facts: True
  tasks:
  - name: Windows | Create local user John Smith
    ansible.windows.win_user:
      fullname: John Smith
      name: John_Smith
      password: P@ssw0rd
      state: present
      groups:
        - Users
        - Remote Desktop Users
  - name: Pass hostname
    ansible.builtin.set_fact:
      VM_hosts: "{{ VM_hosts }}"
    environment:
      no_proxy: "localhost,127.0.0.1"


