- name: Deploy baseline into Windows server 2022
  hosts: windows_group
  tasks:

#control ID: 5263
 
    - name: Obtain current value of No auto-restart with logged on users for scheduled automatic updates
      ansible.windows.win_reg_stat:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: NoAutoRebootWithLoggedOnUsers
      register: current_value_default_5263


    - debug:
        msg: "Control ID: 5263 Display current register key value {{ current_value_default_5263 }}"


    - name: set key value of  No auto-restart with logged on users for scheduled automatic updates
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU\
        name: NoAutoRebootWithLoggedOnUsers
        data: 0

    - name: Obtain current value of No auto-restart with logged on users for scheduled automatic updates
      ansible.windows.win_reg_stat:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: NoAutoRebootWithLoggedOnUsers
      register: reg_key_set_5263

    - debug:
        msg: "Control ID: 5263 Display current register key value of No auto-restart with logged on users for scheduled automatic updates = {{ reg_key_set_5263.value }}"



#Control ID : 7805

    - name: Obtain current value of Windows 'Automatic Updates' (WSUS) setting 
      ansible.windows.win_reg_stat:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: NoAutoUpdate
      register: current_value_default_7805


    - debug: 
        msg: "Control ID: 7805 Display current register key value  {{ current_value_default_7805 }}"


    - name: set key value of  Windows 'Automatic Updates' (WSUS) setting
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU\
        name: NoAutoUpdate
        data: 0

    - name: Obtain current value of Windows 'Automatic Updates' (WSUS) setting
      ansible.windows.win_reg_stat:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: NoAutoUpdate
      register: reg_key_set_7805

    - debug:
        msg: "Control ID: 7805 Display current register key value of Windows 'Automatic Updates' (WSUS) setting ( NoAutoUpdate ) = {{ reg_key_set_7805.value }}"

#control ID: 8248

    - name: Obtain current value of 'Disallow Digest authentication' setting (WinRM client)
      ansible.windows.win_reg_stat:
        path: HKLM:\Software\Policies\Microsoft\Windows\WinRM\Client\
        name: AllowDigest
      register: current_value_default_8248


    - debug:
        msg: "Control ID: 8248 Display current register key value {{ current_value_default_8248 }}"


    - name: set key value of  'Disallow Digest authentication' setting (WinRM client)
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WinRM\Client\
        name: AllowDigest
        data: 0

    - name: Obtain current value of 'Disallow Digest authentication' setting (WinRM client)
      ansible.windows.win_reg_stat:
        path: HKLM:\Software\Policies\Microsoft\Windows\WinRM\Client\
        name: AllowDigest
      register: reg_key_set_8248

    - debug:
        msg: "Control ID: 8248 Display current register key value of 'Disallow Digest authentication' setting (WinRM client) = {{ reg_key_set_8248.value }}"


