---
- name: Create Azure SQL Database
  hosts: localhost
  gather_facts: false
  
  vars:
    resource_group: my_resource_group
    server_name: my_sql_server
    database_name: my_database
    edition: Basic
    collation: SQL_Latin1_General_CP1_CI_AS
      
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: eastus
        
    - name: Create SQL server
      azure_rm_sqlserver:
        resource_group: "{{ resource_group }}"
        name: "{{ server_name }}"
        location: eastus
        version: 12.0
        admin_username: myadmin
        admin_password: mypassword
        
    - name: Create SQL database
      azure_rm_sqldatabase:
        resource_group: "{{ resource_group }}"
        server_name: "{{ server_name }}"
        name: "{{ database_name }}"
        edition: "{{ edition }}"
        collation: "{{ collation }}"
      
    - name: Display SQL database connection string
      debug:
        msg: "SQL Database Connection String: {{ hostvars['localhost']['azure']['sql_database_connection_string'] }}"