---
- name: Delete Azure Storage Account
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: Delete acccount
      azure_rm_storageaccount:
        resource_group: "{{ rg_name }}" 
        name: "{{ storage_account_name }}"
        state: absent
      register: output