---
- name: Delete Web App
  hosts: localhost
  gather_facts: false
   
  vars:
    resource_group: my_resource_group
    storage_account_name: my_storage_account
    location: eastus
    account_type: Standard_LRS

  task:
    - name: Delete acccount
      azure_rm_storageaccount:
        resource_group: "{{ resource_group }}" 
        name: "{{ storage_account_name }}"
        state: absent
      register: output