---
- name: Create Azure Storage Account
  hosts: localhost
  gather_facts: false
  
  vars:
    resource_group: my_resource_group
    storage_account_name: storageacctaap2024
    location: eastus
    account_type: Standard_LRS
  
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
        
    - name: Create storage account
      azure_rm_storageaccount:
        resource_group: "{{ resource_group }}"
        name: "{{ storage_account_name }}"
        account_type: "{{ account_type }}"
        location: "{{ location }}"