- hosts: localhost
  vars:
    resource_group: ResourceGroupAAPtest2024
    location: eastus
    mysqlserver_name: mysqlserveransible
    mysqldb_name: mysqldbansibleaap2024
    admin_username: mysqladmin
    admin_password: P@ssw0rd1234
  tasks:
    - name: Create MySQL Server
      azure_rm_mysqlserver:
        resource_group: "{{ resource_group }}"
        name: "{{ mysqlserver_name }}"
        sku:
          name: B_Gen5_1
          tier: Basic
        location: "{{ location }}"
        version: 5.6
        enforce_ssl: True
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        storage_mb: 51200
    - name: Create instance of MySQL Database
      azure_rm_mysqldatabase:
        resource_group: "{{ resource_group }}"
        server_name: "{{ mysqlserver_name }}"
        name: "{{ mysqldb_name }}"