- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    Azure_rm_resourcegroup:
      name: ResourceGroupAAPLinuxrg
      location: eastus
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: ResourceGroupAAPLinuxrg
      name: myVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: ResourceGroupAAPLinuxrg
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: ResourceGroupAAPLinuxrg
      allocation_method: Static
      name: myPublicIP
    register: output_ip_address
  - name: Public IP of VM
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: ResourceGroupAAPLinuxrg
      name: myNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: ResourceGroupAAPLinuxrg
      name: myNIC
      virtual_network: myVnet
      subnet: mySubnet
      public_ip_name: myPublicIP
      security_group: myNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: ResourceGroupAAPLinuxrg
      name: myVM
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: P@ssw0rd12345
      network_interfaces: myNIC
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest