---
- hosts: localhost
  tasks:
    - name: Deleting resource group - "{{ rg-name }}"
      azure_rm_resourcegroup:
        name: "{{ rg-name }}"
        state: absent
      register: rg
    - debug:
        var: rg