---
- hosts: localhost
  tasks:
    - name: Deleting resource group - "{{ rg_name }}"
      azure_rm_resourcegroup:
        name: "{{ rg_name }}"
        force_delete_nonempty: true
        state: absent
      