---
- name: Modify Azure Key Vault Name
  hosts: localhost
  gather_facts: false

  vars:
    resource_group: my_resource_group
    old_key_vault_name: old_key_vault
    new_key_vault_name: new_key_vault
    azure_tenant_id: 72f98888-8666-4144-9199-2d7cd0111111
    azure_object_id: 99998888-8666-4144-9199-2d7cd0111111

  tasks:
    - name: Create New Key Vault
      azure_rm_keyvault:
        resource_group: "{{ resource_group }}"
        vault_name: "{{ new_key_vault_name }}"
        location: eastus
        sku: 
          name: standard
        access_policies:
          tenant_id: "{{ azure_tenant_id }}"
          object_id: "{{ azure_object_id }}"
        state: present

    - name: Get Secrets from Old Key Vault
      azure_rm_keyvaultsecret_info:
        resource_group: "{{ resource_group }}"
        vault_name: "{{ old_key_vault_name }}"
      register: secrets

    - name: Migrate Secrets
      azure_rm_keyvaultsecret:
        resource_group: "{{ resource_group }}"
        vault_name: "{{ new_key_vault_name }}"
        secret_name: "{{ item.name }}"
        secret_value: "{{ item.value }}"
        state: present
      with_items: "{{ secrets.secrets }}"

    - name: Delete Old Key Vault
      azure_rm_keyvault:
        resource_group: "{{ resource_group }}"
        vault_name: "{{ old_key_vault_name }}"
        state: absent