---
- name: Create Azure Key Vault
  hosts: localhost
  gather_facts: false

  vars:
    resource_group: my_resource_group
    key_vault_name: my_key_vault
    location: eastus
    azure_tenant_id: 2f98888-8666-4144-9199-2d7cd0111111
    azure_object_id: 99998888-8666-4144-9199-2d7cd0111111

  tasks:
    - name: Create Key Vault
      azure_rm_keyvault:
        resource_group: "{{ resource_group }}"
        vault_name: "{{ key_vault_name }}"
        location: "{{ location }}"
        sku: 
          name: standard
          family: A
        access_policies:
          - tenant_id: "{{ azure_tenant_id }}"
          - object_id: "{{ azure_object_id }}"
        state: present