- hosts: localhost
  vars:
    resource_group: ResourceGroupAAPtest2024
    location: eastus 
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
        append_tags: false
