- name: Start Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Start virtual machine
      azure_rm_virtualmachine:
        resource_group: "{{ rg_name }} "
        name: "{{ vm_name }}"
        started: yes