- name: Stop Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Stop virtual machine
      azure_rm_virtualmachine:
        resource_group: "{{ _rg_name }}"
        name: "{{ _vm_name }}"
        allocated: no