---
- name: Create and Update App Service Plans
  hosts: localhost
  gather_facts: false

  vars:
    resource_group: ResourceGroupwebapprg
    Windows_app_service_plan: myAppPlan
    Linux_app_service_plan: LinuxAppPlan
    location: eastus

  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
        tags: 
          application: "AnsibleAAP"

    - name: Create a Windows App Service Plan
      azure_rm_appserviceplan:
        resource_group: "{{ resource_group }}"
        name: "{{ Windows_app_service_plan }}"
        location: "{{ location }}"
        sku: S1

    - name: Create a Linux App Service Plan
      azure_rm_appserviceplan:
        resource_group: "{{ resource_group }}"
        name: "{{ Linux_app_service_plan }}"
        location: "{{ location }}"
        sku: S1
        is_linux: true
        number_of_workers: 1

    - name: Update SKU of existing Windows App Service Plan
      azure_rm_appserviceplan:
        resource_group: "{{ resource_group }}"
        name: "{{ Windows_app_service_plan }}"
        location: "{{ location }}"
        sku: S2

    - name: Create a linux web app with java framework
      azure_rm_webapp:
        resource_group: "{{ resource_group }}"
        name: myLinuxWebapp
        plan:
          resource_group: "{{ resource_group }}"
          name: "{{ Linux_app_service_plan }}"
        app_settings:
          testkey: testvalue
        frameworks:
          - name: "java"
            version: "8"
            settings:
              java_container: "Tomcat"
              java_container_version: "8.5"
  
    - name: Create a linux web app with python framework
      azure_rm_webapp:
        resource_group: "{{ resource_group }}"
        name: myLinuxWebapp_python
        plan:
          resource_group: "{{ resource_group }}"
          name: "{{ Linux_app_service_plan }}"
        app_settings:
          testkey: testvalue
        frameworks:
          - name: "python"
            version: "3.10"
