- name: Create Azure Kubernetes Service
  hosts: localhost
  connection: local
  vars:
    resource_group: Ansible-POC
    location: Switzerland North
    username: azureuser
    ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCxOIvZoEn7QE7DF80+uKJ0SKThClE2xBGjVS8RhjUVLtoUlxA9+o6fGndDuRGj27zxgub9REuZ7G2HNgkGkecXeD76aOJcm4lyhztAwU4Uwmavqjple+W/2Lt8eqhiddLeusjobIj7y6bYr3sQLGaS++A49+JlNxJ185/wzAZtmIWyrUZx3fUZR3jB0A8UY7AjLejdeYNjBE/5727iR7kskNEkIdE5RpZ/L/V2xZk9F/yEzLrPP4lQlLMU0W9PkOOf0yttJJ8GHkPUrdVqxmEKXZgRT3cgA74nWtEf9GLYM+RTDPMcABxiMiozt5joBZir2I1yDWDKo9e55o8x6mssHnp6Y1wZgrGxd/Ml8hTC8trxDv8kP9ccB7S6QGbRHNhhWl2x8d/6OcKdtxWzzjL//pmZWAOutvsiXko7j8ztnq7tn4TQteoZT1iGad6xrMZ1de0YuQjU175uA9MrDZi1Aa3PF5wbwxLXVXi55k06xg9UA3x82JPL0yrlkZt1jk= generated-by-azure
    client_id: "227c41d3-4a02-4f98-bf0f-53c27787587d"
    client_secret: "HGW8Q~1NFGGdBRL-Qf486mtbBgwQTS_tnXj6LbOv"
    aks_name: myAKSCluster
    aks_version: 1.27
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"
  - name: Create a managed Azure Container Services (AKS) cluster
    azure_rm_aks:
      name: "{{ aks_name }}"
      location: "{{ location }}"
      resource_group: "{{ resource_group }}"
      dns_prefix: "{{ aks_name }}"
      kubernetes_version: "{{aks_version}}"
      linux_profile:
        admin_username: "{{ username }}"
        ssh_key: "{{ ssh_key }}"
      service_principal:
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
      agent_pool_profiles:
        - name: default
          count: 2
          vm_size: Standard_D2_v2
      tags:
        Environment: Production
