- name: Docker Uninstallation  
  hosts: dbserver
  become: yes
  tasks:

    
    - name: Uninstall docker
      yum: name={{ item }} 
        state: absent
      loop: [docker-ce , docker-ce-cli , containerd.io , docker-buildx-plugin , docker-compose-plugin]
        
