---
- name: Copy Splunk installation package to Remote system
  hosts: Linux_all
  become: yes
  tasks:
    - name: Copy a file to managed hosts
      ansible.builtin.copy:
        src: /root/software/Splunk/Linux/splunkforwarder-9.1.2-b6b9c8185839.x86_64.rpm
        dest: /tmp/splunkforwarder-9.1.2-b6b9c8185839.x86_64.rpm

    - name: Install Splunk  package.
      yum:
        name: /tmp/splunkforwarder-9.1.2-b6b9c8185839.x86_64.rpm
        state: present


    - name: "Check if Splunk agent is installed"
      package_facts:
        manager: "auto"

    - name: "Splunk agent installation result"
      debug: 
        msg: "Splunk agent installed"
      when: "'splunkforwarder' in ansible_facts.packages"

    - name: "Splunk agent installation result"
      debug: 
        msg: "Splunk agent is not installed"
      when: "'splunkforwarder' not in ansible_facts.packages"
