---

- hosts: windows_group

  tasks:

  - name: Windows | Create local user John Smith
    ansible.windows.win_user:
      fullname: John Smith
      name: John_Smith
      password: P@ssw0rd
      state: present
      groups:
        - Users
        - Remote Desktop Users


