---
- hosts: localhost
  connection: local
  tasks:
    - name: get host list using partial string
      set_fact:
        host_list: "{{ lookup('nios', 'record:host', filter={'name': 'xp-s-netsmtp02z.xp.abb.com'}, provider=nios_provider) }}"

    - name: display host list using partial string
      debug:
        var: host_list 
