---
- hosts: xe-s-vnios01p.xe.abb.com
  tasks:
    - name: get host list using partial string
      set_fact:
        host_list: "{{ lookup('infoblox.nios_modules.nios_lookup', 'record:host', filter={'name':'xp-s-netsmtp02z.xp.abb.com'}, provider=nios_provider) }}"
        nios_provider:
          host: "{{ INFOBLOX_HOSTNAME }}"
          username: "{{ INFOBLOX_USERNAME }}"
          password: "{{ INFOBLOX_PASSWORD }}"
      connection: local
    - name: display host list using partial string
      debug:
        msg: "{{ host_list }}"
