---
#- name: Copy input variable file from gitlab to remote windows server
 # ansible.builtin.copy:
  #   src: XF-S-AAPWIN04T.csv  
   #  dest: C:\temp\

- name: Run PowerShell script to set timezone
  win_shell: |
    $timezoneValue = "{{ input_timezone }}"
    $TZ = Get-TimeZone
    if ($TZ.Id -ne $timezoneValue) {
        Set-TimeZone -Name $timezoneValue
        Write-Host "Timezone set to $timezoneValue"
    } else {
        Write-Host "Timezone already set to $timezoneValue"
    }
  register: powershell_output

- debug:
    msg: "PowerShell output: {{ powershell_output.stdout }}"
      
#- name: Set Timezone using PowerShell script
#  ansible.builtin.script: time_zone.ps1
#  args:
#    Timezone: "{{ input_timezone }}"
