---
#- name: Copy input variable file from gitlab to remote windows server
 # ansible.builtin.copy:
  #   src: XF-S-AAPWIN04T.csv  
   #  dest: C:\temp\

- name: Set Timezone using PowerShell script
  ansible.builtin.script: time_zone.ps1
