---
- name: Copy input variable file from gitlab to remote windows server
  ansible.builtin.copy:
     src: xf-s-aapwin04t.csv
     dest: C:\temp\xf-s-aapwin04t
      
- name: Set Timezone using PowerShell script
  ansible.builtin.script: time_zone_set.ps1
#  args:
#    Timezone: "{{ input_timezone }}"
