---
- name: Adjust Memory , update and close ServiceNow ticket 
  hosts: localhost
  gather_facts: false
  vars:
    sn_impact: medium
    sn_risk: moderate
  tasks:
    - name: Create change request
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"

        type: standard
        state: new
        requested_by: billy-biao.zheng
        short_description: " Adjust Memory on Virtual machine  {{ NOTIFY_HOSTNAME }}  "
        description: " Adjust Memory {{ NOTIFY_HOSTNAME }} "
        priority: moderate
        risk: "{{ sn_risk }}"
        impact: "{{ sn_impact }}"
      delay: 5
      register: _change_ticket  

    - name: Display change ticket number
      ansible.builtin.debug:
        msg: "The change ticket number is  {{ _change_ticket.record.number }} ."

    - name: Pass incident number
      ansible.builtin.set_fact:
        ticket_number: "{{ _change_ticket.record.number }}"

    - name: Look up the virtual machine  in the inventory
      register: search_result
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
        - '{{ NOTIFY_HOSTNAME }}'
      
    - name: Collect information about a specific virtual machine
      vmware.vmware_rest.vcenter_vm_info:
        vm: '{{ search_result.value[0].vm }}'
      register: vm_info

    - name: Get CPU from VM
      vmware.vmware_rest.vcenter_vm_hardware_memory_info:
        vm: '{{ vm_info.id }}'
      register: _Current_MEM_result
      delay: 5


    - name: Change state to scheduled
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"

        state: scheduled
        assignment_group: Wintel
        number: "{{ ticket_number }}"
        other:
          comments: "Ansible automation adjust MEM on host {{ NOTIFY_HOSTNAME }} . Current MEM number is {{ _Current_MEM_result.size_MiB }} MB"
      delay: 5

    - name: Change state to implement
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"

        state: implement
        assignment_group: Wintel
        number: "{{ ticket_number }}"
        other:
          comments: "Ansible automation adjust MEM on host {{ NOTIFY_HOSTNAME }}"


      
    - name: Power off virtual machine
      vmware.vmware_rest.vcenter_vm_power:
        state: stop
        vm: '{{ vm_info.id }}'
      
    - name: Wait until virtual machine offline
      vmware.vmware_rest.vcenter_vm_tools_info:
        vm: '{{ vm_info.id }}'
      register: vm_tools_info
      until:
      - vm_tools_info is not failed
      - vm_tools_info.value.run_state == "NOT_RUNNING"
      retries: 60
      delay: 5      

    - name: Adjust MEM on the VM
      vmware.vmware_rest.vcenter_vm_hardware_memory:
        vm: '{{ vm_info.id }}'
        count: "{{ MEM_number }}"


    - name: Get Memory from VM
      vmware.vmware_rest.vcenter_vm_hardware_memory_info:
        vm: '{{ vm_info.id }}'
      register: _Post_MEM_result



    - name: Power on virtual machine
      vmware.vmware_rest.vcenter_vm_power:
        state: start
        vm: '{{ vm_info.id }}'
      
    - name: Wait until virtual machine is ready
      vmware.vmware_rest.vcenter_vm_tools_info:
        vm: '{{ vm_info.id }}'
      register: vm_tools_info
      until:
      - vm_tools_info is not failed
      - vm_tools_info.value.run_state == "RUNNING"
      retries: 60
      delay: 5      



    - name: change state to review in ServiceNow
      block:
        - name: change state to review 
          servicenow.itsm.change_request:
            instance:
              host: "{{ SN_HOST }}"
              username: "{{ SN_USERNAME }}"
              password: "{{ SN_PASSWORD }}"

            state: review
            close_code: "successful"
            close_notes: "Ansible adjust memory on host {{ NOTIFY_HOSTNAME }} . Host status = {{vm_tools_info.value.run_state}} .Current memory size is {{ _Post_MEM_result.size_MiB }} MB "
            assignment_group: Wintel
            number: "{{ ticket_number }}"
      when: vm_tools_info.value.run_state == "RUNNING"
