---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create new incident
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        state: new
        caller: billy-biao.zheng
        short_description: service stopped
      register: _incident
    
    - name: display incident ticket number
      debug: 
        msg: "The incident number is  {{ _incident.record.number }} ."

