- hosts: "{{ _hostname }}"
  gather_facts: false
  tasks:
    - name: Try to restart {{ _service_name }}
      ansible.windows.win_service:
        name: spooler
        state: restarted
      register: chksrvc
    
    - name: display incident ticket number
      debug: 
        msg: "chksrvc debug info  {{ chksrvc }} ."