---
- name: Set Timezone on Windows
  hosts: all
  gather_facts: no
  tasks:
    - name: Get current timezone
      ansible.windows.win_shell: |
        Get-TimeZone | Select-Object -ExpandProperty Id
      register: current_timezone
      changed_when: false

    - name: Set timezone if not already set
      win_timezone:
        timezone: "{{ input_timezone }}"
      when: current_timezone.stdout != input_timezone
      register: timezone_changed

    - name: Print message if timezone changed
      debug:
        msg: "Timezone set to {{ input_timezone }}"
      when: timezone_changed.changed

    - name: Print message if timezone already set
      debug:
        msg: "Timezone already set to {{ input_timezone }}"
      when: not timezone_changed.changed

