---
- name: Get CD drive details
  win_disk_facts:
  register: cd_drive_facts

- debug: 
    var: cd_drive_facts

- name: Filter CD drive
  set_fact:
    cd_drive_info: "{{ item }}"
  loop: "{{ cd_drive_facts.disks }}"
  when: item.disk_type == 'cd-rom'

- name: Change CD drive letter to Z
  community.windows.win_partition:
    drive_letter: Z
    partition_size: -1
    disk_number: "{{ cd_drive_info.number }}"
    partition_number: 1
  when: cd_drive_info is defined

- name: Display message if no CD drive found
  debug:
    msg: "No CD drive found"
  when: cd_drive_info is not defined
