---
- name: Get raw info to add additional disks 
  set_fact:
     r_partition: "{{ disk_facts.ansible_facts.ansible_disks | selectattr('partition_style', 'eq', 'RAW') | sort(attribute='number') }}"

- name: Get the specific details of RAW
  debug:
    var: r_partition

- name: Initialize raw disks
  win_initialize_disk:
    disk_number: "{{ item.number }}"
    style: gpt
  loop: "{{ r_partition }}"
  loop_control:
    index_var: index

- name: Create and format partitions based on input variables
  block:
    - name: Partition the disks
      win_partition:
        disk_number: "{{ item.number }}"
        partition_size: -1
        drive_letter: "{{ '%c' | format(index + 68) }}"  
        state: present
      loop: "{{ r_partition }}"
      loop_control:
        index_var: index

    - name: Format the partition
      win_format:
        drive_letter: "{{ '%c' | format(index + 68) }}"  
        file_system: NTFS
        new_label: "{{ mrvs_variables[index].disk_label }}"
      loop: "{{ r_partition }}"
      loop_control:
        index_var: index

    - name: Final Disk details
      debug:
        msg: "Disk {{ item.number }} partitioned, formatted and assigned the drive letter as {{ '%c' | format(index + 68) }} with label '{{ mrvs_variables[index].disk_label }}' and size '{{ mrvs_variables[index].disk_size_gb }} GB'"
      loop: "{{ r_partition }}"
      loop_control:
        index_var: index

  when: index < mrvs_variables | length  


   
# - name: Get raw info to add additional disks
#   set_fact:
#      r_partition: "{{ disk_facts.ansible_facts.ansible_disks | selectattr('partition_style', 'eq', 'RAW') | sort(attribute='number') }}"

# - name: Get the specific details of RAW
#   debug:
#     var: r_partition

# - name: Initialize raw disks
#   win_initialize_disk:
#     disk_number: "{{ item.number }}"
#     style: gpt
#   loop: "{{ r_partition }}"
#   loop_control:
#     index_var: index

# - name: Partition the disks
#   win_partition:
#     disk_number: "{{ item.number }}"
#     partition_size: -1
#     drive_letter: "{{ '%c' | format(index + 68) }}"  
#     state: present
#   loop: "{{ r_partition }}"
#   loop_control:
#     index_var: index

# - name: Format the partition
#   win_format:
#     drive_letter: "{{ '%c' | format(index + 68) }}"  
#     file_system: NTFS
#     new_label: "Data"
#   loop: "{{ r_partition }}"
#   loop_control:
#     index_var: index

# - name: Final Disk details
#   debug:
#     msg: "Disk {{ item.number }} partitioned, formatted and assigned the drive letter as {{ '%c' | format(index + 68) }}"
#   loop: "{{ r_partition }}"
#   loop_control:
#     index_var: index
