---
- name: Gather disk facts
  community.windows.win_disk_facts:
  register: disk_facts

- name: Get C partition information
  set_fact:
    c_partition: "{{ disk_facts.ansible_facts.ansible_disks[0].partitions | selectattr('drive_letter', '==', 'C') | first }}"

- name: Resize C partition to maximum supported size if needed
  community.windows.win_partition:
    drive_letter: C
    partition_size: -1
  when:
    - c_partition is defined
    - c_partition.size < c_partition.volumes[0].size_remaining  # Check if current size is less than available size

- name: Display message if C drive expansion is successful
  debug:
    msg: "C: drive expanded successfully"
  when:
    - c_partition is defined
    - c_partition.size < c_partition.volumes[0].size_remaining  # Check if resize was performed

- name: Display message if no action was taken
  debug:
    msg: "C: drive expansion not required or failed"
  when:
    - c_partition is not defined
    - c_partition.size >= c_partition.volumes[0].size_remaining  # Check if no resize was needed
