---
- name: Get next available IP
  set_fact:
    next_ip: "{{ lookup('infoblox.nios_modules.nios_next_ip', '10.17.113.0/24', provider=nios_provider) }}"

- name: Print the next available IP
  debug:
    msg: "Next available IP: {{ next_ip }}"

- set_stats:
     data:
       server_ip: "{{ next_ip }}" 
        
- name: Read CSV file
  community.general.read_csv:
    path: DC1B-VMware-mapping.csv
    delimiter: ','
  register: csv_data

