---
- name: Get current firewall state
  win_shell: |
     Get-NetFirewallProfile -Profile Domain,Public,Private | Select-Object -ExpandProperty Enabled
  register: firewall_state

- name: get the details
  debug: 
    var: firewall_state
