- name: Split DNS suffixes from survey
  set_fact:
    dns_suffix_list: "{{ dns_suffix.split('\\n') }}"

- name: Run PowerShell script to validate DNS suffix
  ansible.windows.win_shell: |
       $DNSSuffix = {{ dns_suffix_list | to_json }}
       $suffixresult = (Get-DnsClientGlobalSetting).SuffixSearchList
       for ($i=0; $i -lt $DNSSuffix.count; $i++) {
           if ($DNSSuffix[$i] -eq $suffixresult[$i]) {
               $a = $suffixresult[$i]
               Write-Output "DNS suffix value $a is correct"
           } else {
               Set-DnsClientGlobalSetting -SuffixSearchList $DNSSuffix
           }
       }
       (Get-DnsClientGlobalSetting).SuffixSearchList
  register: script_output
  when: dns_suffix_list | length > 0
