---
- name: Install Qualys Agent
  win_shell: 'C:\\Temp\\Softwares\\QualysAgent\\QualysCloudAgent.exe /install /passive /norestart /S CustomerId="{{ qualys_customer_id }}" ActivationId="{{ qualys_activation_id }}" WebServiceUri="{{ qualys_webservice_uri }}"'
