---
- name: Install Qualys Cloud Agent
  win_package:
    path: "{{ qualys_agent_path }}"
    arguments:
      - "/install"
      - "/passive"
      - "/norestart"
      - "/S"
      - "CustomerId={{ qualys_customer_id }}"
      - "ActivationId={{ qualys_activation_id }}"
      - "WebServiceUri={{ qualys_webservice_uri }}"
    state: present

- name: Check Installation Status
  win_shell: |
      $agent_installed = Get-ItemProperty -Path "HKLM:\SOFTWARE\Qualys\CloudAgent" -Name "InstallStatus" -ErrorAction SilentlyContinue
      if ($agent_installed -and $agent_installed.InstallStatus -eq "Installed") {
        Write-Host "Qualys Cloud Agent installed successfully."
      } else {
        Write-Host "Qualys Cloud Agent installation failed."
      }
