---
- ansible.windows.win_shell: Get-DnsClientGlobalSetting | Select-Object -ExpandProperty SuffixSearchList
  register: current_suffix

- debug:
     var: current_suffix

- set_fact:
    dns_suffix_list: "{{ dns_suffix | regex_replace('\\\\n', '\\n') | regex_replace('^(.*?)$', '\\1\\n') | trim | split('\\n') }}"

- ansible.windows.win_shell: |
     $DNSSuffix = "{{ dns_suffix_list | join('","') }}"
     $suffixresult = (Get-DnsClientGlobalSetting).SuffixSearchList -split ','
     foreach ($suffix in $DNSSuffix) {
         if ($suffixresult -contains $suffix) {
             Write-Output "DNS suffix value $suffix is correct"
         } else {
             Set-DnsClientGlobalSetting -SuffixSearchList $DNSSuffix
         }
     }
     (Get-DnsClientGlobalSetting).SuffixSearchList
  register: script_output
  when: dns_suffix_list | length > 0

- debug:
     msg: "{{ script_output.stdout }}"
  ignore_errors: yes
