---
- name: Install Qualys Agent
  win_package:
     path: "{{ qualys_agent_path }}"
     arguments:
        - /install
        - /passive
        - /norestart
        - /S
        - CustomerId="{{ customer_id }}"
        - ActivationId="{{ activation_id }}"
        - WebServiceUri="{{ web_service_uri }}"
  state: present
