---
- name: Get disk facts
  win_disk_facts:
  register: disk_facts

- debug:
    var: disk_facts
- name: Get raw info
  set_fact:
     r_partition: "{{ ansible_facts.ansible_disks | selectattr('partition_style', 'eq', 'RAW') | sort(attribute='number') }}"

- name: get the specific details of RAW
  debug:
    var: r_partition
