---
- name: Install FlexNet Agent
  win_command: cmd /c C:\Temp\Softwares\Flexnet-Windows-2021-R1\Windows\Install.cmd /quiet /norestart
  async: 30
  poll: 0

- name: Wait for 30 seconds
  pause:
    seconds: 30

- name: Verify FlexNet Agent installation
  win_stat:
    path: C:\Program Files (x86)\ManageSoft\Policy Client\mgspolicy.exe
  register: mgspolicy

- name: Verify FlexNet Agent installation
  win_stat:
    path: C:\Program Files (x86)\ManageSoft\Tracker\ndtrack.exe
  register: ndtrack

- name: Start FlexNet Agent services
  win_service:
    name: mgspolicy
    state: started
  when: mgspolicy.stat.exists

- name: Start FlexNet Agent services
  win_service:
    name: ndtrack
    state: started
  when: ndtrack.stat.exists
