---
- name: Install FlexNet Agent
  win_shell: cmd /c C:\Temp\Softwares\Flexnet-Windows-2021-R1\Windows\Install.cmd /quiet /norestart
  async: 180
  poll: 10

- name: Wait for 30 seconds
  pause:
    seconds: 10

- name: Verify FlexNet Agent installation
  win_stat:
    path: C:\Program Files (x86)\ManageSoft\Policy Client\mgspolicy.exe
  register: mgspolicy

- name: Verify FlexNet Agent installation
  win_stat:
    path: C:\Program Files (x86)\ManageSoft\Tracker\ndtrack.exe
  register: ndtrack

- name: Check if FlexNet policy and tracker files exist
  win_stat:
    path: "{{ item }}"
  loop:
    - "C:\\Program Files (x86)\\ManageSoft\\Policy Client\\mgspolicy.exe"
    - "C:\\Program Files (x86)\\ManageSoft\\Tracker\\ndtrack.exe"
  register: flexnet_files

- name: Install FlexNet policy and tracker files
  win_command:
    cmd: "{{ item.item }}"
    arguments: "-t Machine -o userinteractionlevel=quiet"
  when: item.stat.exists
  loop: "{{ flexnet_files.results }}"

- name: Start FlexNet services
  win_service:
    name: "{{ item }}"
    state: started
  loop:
    - "FlexNet Policy Client"
    - "FlexNet Tracker"
  ignore_errors: yes

- name: Start FlexNet Agent services
  win_service:
    name: mgspolicy
    state: started
  when: mgspolicy.stat.exists

- name: Start FlexNet Agent services
  win_service:
    name: ndtrack
    state: started
  when: ndtrack.stat.exists
