---

- name: Check if FlexNet Agent is already installed
  win_stat:
    path: "C:\\Program Files (x86)\\ManageSoft"  
  register: flexnet_installed

- name: Skip FlexNet Agent installation if already installed
  debug:
    msg: "FlexNet Agent is already installed, skipping installation"
  when: flexnet_installed.stat.exists
  
- name: Install FlexNet Agent
  win_shell: cmd /c "{{ flexnet_binary_file_path }}" /quiet /norestart
  async: 180
  poll: 10
  when: not flexnet_installed.stat.exists

- name: Wait for 10 seconds
  pause:
    seconds: 10
  when: not flexnet_installed.stat.exists

- name: Check if FlexNet policy and tracker files exist
  win_stat:
    path: "{{ item }}"
  loop:
    - "{{ mgspolicy_file_path }}"
    - "{{ ndtrack_file_path }}"
  register: flexnet_files
  when: not flexnet_installed.stat.exists

- name: Log - Flexnet policy and tracker files are available
  debug:
    msg: "Flexnet policy and tracker files are available and continuing the installation"
  when: flexnet_files.results | map(attribute='stat.exists') | list == [true] * flexnet_files.results | length and not flexnet_installed.stat.exists

- name: Start FlexNet Agent Installation
  win_shell: |
    "{{ item.item }} -t Machine -o userinteractionlevel=quiet"
  loop: "{{ flexnet_files.results }}"
  when: flexnet_files.results | map(attribute='stat.exists') | list == [true] * flexnet_files.results | length and not flexnet_installed.stat.exists
