---
- name: Check Defender service status before onboarding
  ansible.windows.win_service:
    name: WinDefend
  register: defender_service_status_before

- name: Write log - Onboarding Defender started
  win_shell: Write-Host "Onboarding Defender started"

- name: Run onboarding script
  win_shell: |
    Start-Process {{ defender_script_path }}
    Start-Sleep -Seconds 60

- name: Check Defender service status after onboarding
  ansible.windows.win_service:
    name: WinDefend
  register: defender_service_status_after

- name: Write log - Onboarding Defender completed
  win_shell: Write-Host "Onboarding Defender completed"

- name: Display Defender service status before and after onboarding
  debug:
    msg: "Defender service status before onboarding: {{ defender_service_status_before.status }}, after onboarding: {{ defender_service_status_after.status }}"
