---
- name: Get disk facts
  win_disk_facts:
  register: disk_facts

- name: display disk facts
  debug:
    var: disk_facts
    
- name: Display unallocated space
  debug:
      msg: "Unallocated space in Disk 0: {{ ansible_mounts | json_query('[?mount==`C:`].size_available') }}"
