---
- name: Get current firewall state
  win_shell: |
     Get-NetFirewallProfile -Profile Domain,Public,Private | Select-Object -ExpandProperty Enabled
  register: pre_firewall_state

- name: get the details
  debug: 
    var: pre_firewall_state

- name: Display message if firewall is already enabled
  debug:
     msg: "Firewall state is currently enabled"
  when: "'True' in pre_firewall_state.stdout"

- name: Disable Windows Firewall
  win_firewall:
     profile: all
     state: disabled
  when: "'True' in pre_firewall_state.stdout"

- name: Get current firewall state again
  win_shell: |
     Get-NetFirewallProfile -Profile Domain,Public,Private | Select-Object -ExpandProperty Enabled
  register: post_firewall_state
  when: "'True' in pre_firewall_state.stdout"

- name: Display message if firewall is successfully disabled
  debug:
     msg: "Firewall state is disabled"
  when: "'False' in post_firewall_state.stdout"
  ignore_errors: yes
