---
- name: Install Qualys Agent
  win_shell: 'C:\\Temp\\Softwares\\QualysAgent\\QualysCloudAgent.exe /install /passive /norestart /S CustomerId="{{ customer_id }}" ActivationId="{{ activation_id }}" WebServiceUri="{{ web_service_uri }}"'
