---
- name: Onboarding the windows defender
  win_command: "{{ defender_script_path }}"
  async: 60
  poll: 0

- win_shell: "echo 'Waiting for 60 seconds...' && sleep 60"

- win_shell: "echo 'Checking onboarding status...' && defender_onboarding_status_command"
  register: onboarding_status

- win_shell: "echo 'Onboarding Defender completed with status: {{ onboarding_status.stdout }}'"
