---
- name: Get current DNS suffixes
  win_dns_client:
     adapter_names: '*'
  register: current_suffixes

- name: Set DNS suffixes
  win_dns_client:
     adapter_names: '*'
     dns_suffixes:
        - xf.abb.com
        - europe.abb.com
        - abb.com
  when: current_suffixes.dns_suffixes != ['xf.abb.com', 'europe.abb.com', 'abb.com']

- name: Verify DNS suffixes
  win_dns_client:
     adapter_names: '*'
  register: new_suffixes

- name: Log DNS suffixes
  debug:
     msg: "DNS suffixes set to {{ new_suffixes.dns_suffixes }}"
