---
- name: Get current DNS suffix search list
  ansible.windows.win_shell: Get-DnsClientGlobalSetting | Select-Object -ExpandProperty SuffixSearchList
  register: current_suffix

- debug:
    var: current_suffix

- name: Parse DNS suffixes
  set_fact:
    dns_suffixes_list: "{{ dns_suffixes.splitlines() }}"

- name: Run PowerShell script to validate DNS suffix
  ansible.windows.win_shell: |
       $DNSSuffix = "{{ dns_suffixes_list }}"
       $suffixresult = "{{ current_suffix.stdout }}"
       foreach ($dns_suffix in $DNSSuffix) {
       $suffixes = $suffixresult -split "\r?\n"
            if ($dns_suffix -notin $suffixes) {
                Set-DnsClientGlobalSetting -SuffixSearchList $dns_suffix
            }
       }
       Get-DnsClientGlobalSetting | Select-Object -ExpandProperty SuffixSearchList
  register: script_output
  when: dns_suffixes_list | select('in', current_suffix.stdout) | length == 0

- debug:
     msg: "{{ script_output.stdout }}"
  ignore_errors: yes
