---
- name: Install FlexNet Agent
  win_package:
    path: "{{ flex_install_pth }}"
    state: present

- name: Configure FlexNet Agent Policy
  win_copy:
    content: |
      [FlexNet Agent Policy]
      PolicyFile = {{ mgspolicy_pth }}
    dest: C:\Program Files\Flexera Software\Inventory Agent\policy.cfg

- name: Configure FlexNet Agent Tracker
  win_copy:
    content: |
      [FlexNet Agent Tracker]
      TrackerFile = {{ ndtrack_pth }}
    dest: C:\Program Files\Flexera Software\Inventory Agent\tracker.cfg

- name: Start FlexNet Agent Service
  win_service:
    name: FlexNet Inventory Agent
    state: started

- name: Verify FlexNet Agent Installation
  win_shell:
    cmd: tasklist /fi "imagename eq ndinit.exe" |find ":" > nul
    register: result
  failed_when: result.rc != 0

- name: Verify FlexNet Agent Upload
  win_shell:
    cmd: Select-String -Path C:\Windows\Temp\ManageSoft\uploader.log -Pattern "Upload successful"
    register: result
  failed_when: result.rc != 0
