---
- name: Get current DNS suffix search list
  ansible.windows.win_shell: Get-DnsClientGlobalSetting | Select-Object -ExpandProperty SuffixSearchList
  register: current_suffix

- debug:
    var: current_suffix

- name: Run PowerShell script to validate DNS suffix
  ansible.windows.win_shell: |
       $DNSSuffix = "{{ dns_suffix }}"
       $suffixresult = "{{ current_suffix.stdout }}"
       foreach ($dns_suffix in $DNSSuffix) {
            if ($suffixresult -notcontains $dns_suffix) {
                Set-DnsClientGlobalSetting -SuffixSearchList $dns_suffix
            }
       }
       Get-DnsClientGlobalSetting | Select-Object -ExpandProperty SuffixSearchList
  register: script_output
  when: current_suffix.stdout is not search(dns_suffix)
#  ignore_errors: yes

- debug:
     msg: "{{ script_output.stdout }}"
#  when: script_output|changed
  ignore_errors: yes
