---
- name: Log installation starting
  win_shell: Write-Host "Qualys agent installation starting"

- name: Install Qualys Cloud Agent
  win_shell: |
      Start-Process -FilePath "{{ qualys_agent_installation_path }}" -ArgumentList "CustomerId={{ qualys_customer_id }} ActivationId={{ qualys_activation_id }} WebServiceUri={{ qualys_webservice_uri }}" -Wait

- name: Log installation completed
  win_shell: Write-Host "Qualys agent installation completed"
