---
- name: Install Qualys Agent
  win_package:
     path: "{{ qualys_agent_installation_path }}"
     arguments:
        - /install
        - /passive
        - /norestart
        - /S
        - CustomerId="{{ qualys_customer_id }}"
        - ActivationId="{{ qualys_activation_id }}"
        - WebServiceUri="{{ qualys_webservice_uri }}"
     state: present
