---
- name: Check if FlexNet Agent is already installed
  win_stat:
    path: "{{ felxnet_installed_path }}"  
  register: flexnet_installed
  
- name: Install FlexNet Agent
  win_shell: cmd /c "{{ flexnet_binary_file_path }}" /quiet /norestart
  async: 180
  poll: 10
  when: not flexnet_installed.stat.exists

- name: Wait for 10 seconds post installation
  pause:
    seconds: 10
  when: not flexnet_installed.stat.exists

- name: Check if FlexNet policy and tracker files exist
  win_stat:
    path: "{{ item }}"
  loop:
    - "{{ mgspolicy_file_path }}"
    - "{{ ndtrack_file_path }}"
  register: flexnet_files

- name: Start FlexNet Agent Installation
  win_shell: |
    "{{ item.item }} -t Machine -o userinteractionlevel=quiet"
  loop: "{{ flexnet_files.results }}"
  when: flexnet_files.results | map(attribute='stat.exists') | list == [true] * flexnet_files.results | length
