---
- name: 
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  tasks:
    - name: Gather info about all content_library
      community.vmware.vmware_content_library_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
      register: content_library_info

    - name: print content_library info
      ansible.builtin.debug:
        var: content_library_info