---
- name: Collect  information
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Look up the VM  in the inventory
      register: search_result
      vmware.vmware_rest.vcenter_vm_info:
        filter_names:
        - '{{ _vm }}'

    - name: Collect information about a specific VM
      vmware.vmware_rest.vcenter_vm_info:
        vm: '{{ search_result.value[0].vm }}'
      register: test_vm1_info

    - name: Get guest power information
      vmware.vmware_rest.vcenter_vm_power_info:
        vm: '{{ test_vm1_info.id }}'
      register: _result
    
    - name: print VM power status
      ansible.builtin.debug:
        var: _result.state