---
- name: vmware guest tools info demo
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - community.vmware
#  pre_tasks:
#    - include_vars: vars.yml
  tasks:
    - name: guest tools info
      community.vmware.vmware_guest_tools_info:
#        hostname: "{{ vcenter_hostname }}"
#        username: "{{ vcenter_username }}"
#        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ vm_name }}"
      register: vmtools_info

    - name: print guest tools info
      ansible.builtin.debug:
        var: vmtools_info
