---
- name: Get current firewall status
  win_firewall:
    profile: all
    state: query
  register: firewall_status

- name: Display message if firewall is already disabled
  debug:
     msg: "Firewall is already disabled"
  when: firewall_status.current_state == 'disabled'

- name: Disable Windows Firewall
  win_firewall:
     profile: all
     state: disabled
  when: firewall_status.current_state != 'disabled'
