---
- name: Get current firewall state
  win_shell: |
     Get-NetFirewallProfile -Profile Domain,Public,Private | Select-Object -ExpandProperty Enabled
  register: firewall_state

- name: Display message if firewall is already disabled
  debug:
     msg: "Firewall is already disabled"
  when: firewall_state.stdout == 'False'

- name: Disable Windows Firewall
  win_firewall:
     profile: all
     state: disabled
  when: firewall_state.stdout != 'False'
