---
- name: Get current firewall state
  win_shell: |
     Get-NetFirewallProfile -Profile Domain,Public,Private | Select-Object -ExpandProperty Enabled
  register: firewall_state

- name: Debug firewall state
  debug:
    var: firewall_state.stdout

- name: Display message if firewall is already disabled
  debug:
     msg: "Firewall is already disabled"
  when: "'False' in firewall_state.stdout"

- name: Disable Windows Firewall
  win_firewall:
     profile: all
     state: disabled
  when: "'True' in firewall_state.stdout"
