---
# win baseline 1149 state
- name: "win_baseline_1149_state | Ensure 'Microsoft network client - Digitally sign communications (always)' is set to 'Enabled'"
  win_regedit:
    path: "{{ win_baseline_1149_state_Path }}"
    name: "{{ win_baseline_1149_state_Name}}"
    data: "{{ win_baseline_1149_state_Data }}"
    type: "{{ win_baseline_1149_state_Type }}"
  when:
    win_baseline_1149_state_Manage

# - name: "windows_baseline_19336_state"
#   win_regedit:
#     path: "{{ windows_baseline_19336_state_Path }}"
#     name: "{{ windows_baseline_19336_state_Name }}"
#     data: "{{ windows_baseline_19336_state_Data }}"
#     type: "{{ windows_baseline_19336_state_Type }}"
#   when: windows_baseline_19336_state_Manage

# win baseline 1153 state
- name: "win_baseline_1153_state | Ensure 'Network access: Do not allow anonymous enumeration of SAM accounts' is set to 'Enabled'"
  win_regedit:
    path: "{{ win_baseline_1153_state_Path }}"
    name: "{{ win_baseline_1153_state_Name }}"
    data: "{{ win_baseline_1153_state_Data }}"
    type: "{{ win_baseline_1153_state_Type }}"
  when:
    win_baseline_1153_state_Manage