- name: Install mariadb-server on the db server
  hosts: dbserver
  become: true
  tasks:
    - name: Install the latest version of mariadb-server
      yum:
        name: mariadb-server
        state: latest

    - name: start up Mariadb service  
      service:
        name: mariadb
        enabled: true
        state: started
      register: mariadb_status

    - debug:
        var: mariadb_status

