---
- name: Install and start Apache HTTPD
  become: true
  hosts: "{{ _hosts }}"
  tasks:
    - name: httpd service installing
      yum:
        name:
          - httpd
        state: present
      environment:
        http_proxy: http://ssoibmlnx:TYqQ2DJ0@xe-s-lnxjump1.xe.abb.com:3128
        https_proxy: http://ssoibmlnx:TYqQ2DJ0@xe-s-lnxjump1.xe.abb.com:3128

    - name: Create an Index.HTML File
      copy:
        content: This is a test page for Furture Hosting Model managed by Ansible  
        dest: /var/www/html/index.html

    - name: httpd is started
      service:
        name: httpd
        state: started
        enabled: true
      register: httpd_status

    - debug:
        var: httpd_status

