---
- name: 
  hosts: "{{ _hosts }}"
  become: yes
  tasks:
    - name: Copy Splunk installation package to Remote system
      ansible.builtin.copy:
        src: "/tmp/linux/Splunk/Linuxsplunkforwarder-9.1.2-b6b9c8185839.x86_64.rpm"
        dest: /tmp/splunkforwarder-9.1.2-b6b9c8185839.x86_64.rpm

    - name: Install Splunk  package.
      yum:
        name: /tmp/splunkforwarder-9.1.2-b6b9c8185839.x86_64.rpm
        state: present
        disable_gpg_check: true


    - name: "Check if Splunk agent is installed"
      package_facts:
        manager: "auto"

    - name: "Splunk agent installation result"
      debug: 
        msg: "Splunk agent installed"
      when: "'splunkforwarder' in ansible_facts.packages"

    - name: "Splunk agent installation result"
      debug: 
        msg: "Splunk agent is not installed"
      when: "'splunkforwarder' not in ansible_facts.packages"
