---
- name: Get the powershell template for timezone change
  template:
    src: time_zone.ps1.j2
    dest: C:\temp\time_zone.ps1

- name: Run PowerShell script to set timezone
  win_shell: |
      powershell -File C:\temp\time_zone.ps1
  register: timezone_output

- debug:
    msg: "Change status: {{ timezone_output.stdout }}"

- name: Delete PowerShell script from server
  win_file:
    path: C:\temp\time_zone.ps1
    state: absent
    
- name: Copy input variable file from gitlab to windows server
  ansible.builtin.copy:
     src: XF-S-AAPWIN04T.csv  
     dest: C:\temp\
     
- name: Testing the dns_suffix
  ansible.builtin.script: dns_suffix.ps1


