---
- name: Add new server to Science Logic and fetch server details
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Add new server to Science Logic
      uri:
        url: "{{ device_url }}"
        method: POST
        body:
          name: "{{ server_name }}"
          ip_lists: [
            {
              start_ip: "{{ start_ip }}",
              end_ip: "{{ end_ip }}"
            }
          ]
          organization: "/api/organization/2"
          aligned_collector: "/api/appliance/25"
          aligned_device_template: "/api/device_template/20"
          description: "xf-s-aapwin04t addition using Ansible Automation"
          device_groups: [
            "/api/device_group/EFBB8064997E7F0133796335146DDCF5"
          ]
          credentials: [
            "/api/credential/snmp/3074E50E642F46E786C443BB187F9CDE"
          ]
        body_format: json
        headers:
          Content-Type: "application/json"
        user: "{{ username }}"
        password: "{{ password }}"
      register: add_server_response
      ignore_errors: yes

    - debug:
        var: add_server_response

    - name: Fetch server details
      uri:
        url: "{{ device_url }}{{ add_server_response.json.id }}/"
        method: GET
        return_content: yes
        status_code: 200
        headers:
          Content-Type: "application/json"
        user: "{{ username }}"
        password: "{{ password }}"
      register: server_details
      ignore_errors: yes

    - debug:
        var: server_details
        
