---
- name: Create server maintenance task and schedule
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Login to device
    uri:
      url: "{{ device_url }}"
      method: GET
      return_content: yes
      status_code: 200
      headers:
        Content-Type: "application/xml"
      body_format: form-urlencoded
      user: "{{ username }}"
      password: "{{ password }}"
    register: login_response

  - name: Create task
    uri:
      url: https://test.monitoring.abb.com/api/task/
      method: POST
      body_format: json
      body:
        name: "Automation Ansible testing"
        description: "Creating the task id"
        enabled: "1"
        details:
          active: "12"
          patch_window: "0"
        last_run: "0"
        owner: "/api/account/20"
        organization: "/api/organization/1"
        visibility: "Organization"
        aligned_resource: "/api/device/9222"
      status_code: 201
      headers:
        Content-Type: "application/json"
      user: "{{ username }}"
      password: "{{ password }}"
    register: task_response

  - name: Extract task ID
    set_fact:
       task_id: "{{ task_response.json.schedules.URI | regex_search('task/([0-9]+)', '\\1') }}"

  - ansible.builtin.set_stats:
      data:
        tasks_id: "{{ task_id }}"
   


  # - name: Extract task ID
  #   set_fact:
  #      task_id: "{{ task_response.json.schedules.URI | regex_search('task/([0-9]+)') }}"

  # - name: Extract task ID
  #   set_fact:
  #     task_id: "{{ task_response.json.schedules.URI | regex_search('task\\/([0-9]+') | regex_replace('task/', '') }}"
    
  # - name: Get task details
  #   debug: var=task_response
