---
- name: VM from template
  hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - ansible.windows
    - community.vmware
    - community.windows
    -  community.general
  tasks:

  - name: testing
    ansible.builtin.import_role:
      name: pre_test

  - name: testing
    ansible.builtin.import_role:
      name: pre_test


