---
- name: windows post provisioning  
  hosts: all
  gather_facts: no
  collections:
    - ansible.windows
  tasks:

  - name: Validate and Modify the system timezone
    ansible.builtin.import_role:
      name: timezone

  - name: Validate and Modify the system timezone
    ansible.builtin.import_role:
      name: kms_registration

  - name: Validate and Modify the system timezone
    ansible.builtin.import_role:
      name: enable_rdp
