---
- name: windows post provisioning  
  hosts: all
  gather_facts: no
  collections:
    - ansible.windows
  tasks:

  - name: Validate and set the system timezone
    ansible.builtin.import_role:
      name: disk_management


