---
- name: VM from template
  hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - ansible.windows
    - community.vmware
    - community.windows
    - community.general
  tasks:

  - name: Read the CSV input
    ansible.builtin.import_role:
      name: read_csv

#  - name: Build the VM server
 #   ansible.builtin.import_role:
 #     name: pre_test


